<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\District;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $collection = collect(array(
            array('id' => '1','state_id' => '33','name' => 'Nicobar','status' => '1'),
            array('id' => '2','state_id' => '33','name' => 'North and Middle Andaman','status' => '1'),
            array('id' => '3','state_id' => '33','name' => 'South Andaman','status' => '1'),
            array('id' => '4','state_id' => '1','name' => 'Anantapur','status' => '1'),
            array('id' => '5','state_id' => '1','name' => 'Chittoor','status' => '1'),
            array('id' => '6','state_id' => '1','name' => 'East Godavari','status' => '1'),
            array('id' => '7','state_id' => '1','name' => 'Guntur','status' => '1'),
            array('id' => '8','state_id' => '1','name' => 'YSR(Kadapa)','status' => '1'),
            array('id' => '9','state_id' => '1','name' => 'Krishna','status' => '1'),
            array('id' => '10','state_id' => '1','name' => 'Kurnool','status' => '1'),
            array('id' => '11','state_id' => '1','name' => 'Prakasam','status' => '1'),
            array('id' => '12','state_id' => '1','name' => 'Sri Potti Sriramulu Nellore','status' => '1'),
            array('id' => '13','state_id' => '1','name' => 'Srikakulam','status' => '1'),
            array('id' => '14','state_id' => '1','name' => 'Visakhapatnam','status' => '1'),
            array('id' => '15','state_id' => '1','name' => 'Vizianagaram','status' => '1'),
            array('id' => '16','state_id' => '1','name' => 'West Godavari','status' => '1'),
            array('id' => '17','state_id' => '2','name' => 'Anjaw','status' => '1'),
            array('id' => '18','state_id' => '2','name' => 'Changlang','status' => '1'),
            array('id' => '19','state_id' => '2','name' => 'East Kameng','status' => '1'),
            array('id' => '20','state_id' => '2','name' => 'East Siang','status' => '1'),
            array('id' => '21','state_id' => '2','name' => 'Kamle','status' => '1'),
            array('id' => '22','state_id' => '2','name' => 'Shi Yomi','status' => '1'),
            array('id' => '23','state_id' => '2','name' => 'Pakke Kessang','status' => '1'),
            array('id' => '24','state_id' => '2','name' => 'Lohit','status' => '1'),
            array('id' => '25','state_id' => '2','name' => 'Longding','status' => '1'),
            array('id' => '26','state_id' => '2','name' => 'Lower Dibang Valley','status' => '1'),
            array('id' => '27','state_id' => '2','name' => 'Lower Siang','status' => '1'),
            array('id' => '28','state_id' => '2','name' => 'Lower Subansiri','status' => '1'),
            array('id' => '29','state_id' => '2','name' => 'Namsai','status' => '1'),
            array('id' => '30','state_id' => '2','name' => 'Leparada','status' => '1'),
            array('id' => '31','state_id' => '2','name' => 'Siang','status' => '1'),
            array('id' => '32','state_id' => '2','name' => 'Tawang','status' => '1'),
            array('id' => '33','state_id' => '2','name' => 'Tirap','status' => '1'),
            array('id' => '34','state_id' => '2','name' => 'Dibang Valley','status' => '1'),
            array('id' => '35','state_id' => '2','name' => 'Upper Siang','status' => '1'),
            array('id' => '36','state_id' => '2','name' => 'Upper Subansiri','status' => '1'),
            array('id' => '37','state_id' => '2','name' => 'West Kameng','status' => '1'),
            array('id' => '38','state_id' => '2','name' => 'West Siang','status' => '1'),
            array('id' => '39','state_id' => '3','name' => 'Baksa','status' => '1'),
            array('id' => '40','state_id' => '3','name' => 'Barpeta','status' => '1'),
            array('id' => '42','state_id' => '3','name' => 'Bongaigaon','status' => '1'),
            array('id' => '43','state_id' => '3','name' => 'Cachar','status' => '1'),
            array('id' => '44','state_id' => '3','name' => 'Charaideo','status' => '1'),
            array('id' => '45','state_id' => '3','name' => 'Chirang','status' => '1'),
            array('id' => '46','state_id' => '3','name' => 'Darrang','status' => '1'),
            array('id' => '47','state_id' => '3','name' => 'Dhemaji','status' => '1'),
            array('id' => '48','state_id' => '3','name' => 'Dhubri','status' => '1'),
            array('id' => '49','state_id' => '3','name' => 'Dibrugarh','status' => '1'),
            array('id' => '50','state_id' => '3','name' => 'Dima Hasao','status' => '1'),
            array('id' => '51','state_id' => '3','name' => 'Goalpara','status' => '1'),
            array('id' => '52','state_id' => '3','name' => 'Golaghat','status' => '1'),
            array('id' => '53','state_id' => '3','name' => 'Hailakandi','status' => '1'),
            array('id' => '55','state_id' => '3','name' => 'Jorhat','status' => '1'),
            array('id' => '56','state_id' => '3','name' => 'Kamrup','status' => '1'),
            array('id' => '57','state_id' => '3','name' => 'Kamrup Metropolitan','status' => '1'),
            array('id' => '58','state_id' => '3','name' => 'Karbi Anglong','status' => '1'),
            array('id' => '59','state_id' => '3','name' => 'Karimganj','status' => '1'),
            array('id' => '60','state_id' => '3','name' => 'Kokrajhar','status' => '1'),
            array('id' => '61','state_id' => '3','name' => 'Lakhimpur','status' => '1'),
            array('id' => '62','state_id' => '3','name' => 'Majuli','status' => '1'),
            array('id' => '63','state_id' => '3','name' => 'Morigaon','status' => '1'),
            array('id' => '64','state_id' => '3','name' => 'Nagaon','status' => '1'),
            array('id' => '65','state_id' => '3','name' => 'Nalbari','status' => '1'),
            array('id' => '66','state_id' => '3','name' => 'Sibsagar','status' => '1'),
            array('id' => '67','state_id' => '3','name' => 'South Salmara-Mankachar','status' => '1'),
            array('id' => '68','state_id' => '3','name' => 'Sonitpur','status' => '1'),
            array('id' => '69','state_id' => '3','name' => 'Tinsukia','status' => '1'),
            array('id' => '70','state_id' => '3','name' => 'Udalguri','status' => '1'),
            array('id' => '71','state_id' => '3','name' => 'West Karbi Anglong','status' => '1'),
            array('id' => '72','state_id' => '4','name' => 'Araria','status' => '1'),
            array('id' => '73','state_id' => '4','name' => 'Arwal','status' => '1'),
            array('id' => '74','state_id' => '4','name' => 'Aurangabad','status' => '1'),
            array('id' => '75','state_id' => '4','name' => 'Banka','status' => '1'),
            array('id' => '76','state_id' => '4','name' => 'Begusarai','status' => '1'),
            array('id' => '77','state_id' => '4','name' => 'Bhagalpur','status' => '1'),
            array('id' => '78','state_id' => '4','name' => 'Bhojpur','status' => '1'),
            array('id' => '79','state_id' => '4','name' => 'Buxar','status' => '1'),
            array('id' => '80','state_id' => '4','name' => 'Darbhanga','status' => '1'),
            array('id' => '81','state_id' => '4','name' => 'Purvi Champaran','status' => '1'),
            array('id' => '82','state_id' => '4','name' => 'Gaya','status' => '1'),
            array('id' => '83','state_id' => '4','name' => 'Gopalganj','status' => '1'),
            array('id' => '84','state_id' => '4','name' => 'Jamui','status' => '1'),
            array('id' => '85','state_id' => '4','name' => 'Jehanabad','status' => '1'),
            array('id' => '86','state_id' => '4','name' => 'Kaimur','status' => '1'),
            array('id' => '87','state_id' => '4','name' => 'Katihar','status' => '1'),
            array('id' => '88','state_id' => '4','name' => 'Khagaria','status' => '1'),
            array('id' => '89','state_id' => '4','name' => 'Kishanganj','status' => '1'),
            array('id' => '90','state_id' => '4','name' => 'Lakhisarai','status' => '1'),
            array('id' => '91','state_id' => '4','name' => 'Madhepura','status' => '1'),
            array('id' => '92','state_id' => '4','name' => 'Madhubani','status' => '1'),
            array('id' => '93','state_id' => '4','name' => 'Munger','status' => '1'),
            array('id' => '94','state_id' => '4','name' => 'Muzaffarpur','status' => '1'),
            array('id' => '95','state_id' => '4','name' => 'Nalanda','status' => '1'),
            array('id' => '96','state_id' => '4','name' => 'Nawada','status' => '1'),
            array('id' => '97','state_id' => '4','name' => 'Patna','status' => '1'),
            array('id' => '98','state_id' => '4','name' => 'Purnia','status' => '1'),
            array('id' => '99','state_id' => '4','name' => 'Rohtas','status' => '1'),
            array('id' => '100','state_id' => '4','name' => 'Saharsa','status' => '1'),
            array('id' => '101','state_id' => '4','name' => 'Samastipur','status' => '1'),
            array('id' => '102','state_id' => '4','name' => 'Saran','status' => '1'),
            array('id' => '103','state_id' => '4','name' => 'Sheikhpura','status' => '1'),
            array('id' => '104','state_id' => '4','name' => 'Sheohar','status' => '1'),
            array('id' => '105','state_id' => '4','name' => 'Sitamarhi','status' => '1'),
            array('id' => '106','state_id' => '4','name' => 'Siwan','status' => '1'),
            array('id' => '107','state_id' => '4','name' => 'Supaul','status' => '1'),
            array('id' => '108','state_id' => '4','name' => 'Vaishali','status' => '1'),
            array('id' => '109','state_id' => '4','name' => 'Paschim Champaran','status' => '1'),
            array('id' => '110','state_id' => '34','name' => 'Chandigarh','status' => '1'),
            array('id' => '111','state_id' => '5','name' => 'Balod','status' => '1'),
            array('id' => '112','state_id' => '5','name' => 'Balodbazar - Bhatapara','status' => '1'),
            array('id' => '113','state_id' => '5','name' => 'Balramapur','status' => '1'),
            array('id' => '114','state_id' => '5','name' => 'Bastar (Jagdalpur)','status' => '1'),
            array('id' => '115','state_id' => '5','name' => 'Bemetara','status' => '1'),
            array('id' => '116','state_id' => '5','name' => 'Bijapur','status' => '1'),
            array('id' => '117','state_id' => '5','name' => 'Bilaspur','status' => '1'),
            array('id' => '118','state_id' => '5','name' => 'Dakshin Bastar Dantewada','status' => '1'),
            array('id' => '119','state_id' => '5','name' => 'Dhamtari','status' => '1'),
            array('id' => '120','state_id' => '5','name' => 'Durg','status' => '1'),
            array('id' => '121','state_id' => '5','name' => 'Gariyaband','status' => '1'),
            array('id' => '122','state_id' => '5','name' => 'Janggir-Champa','status' => '1'),
            array('id' => '123','state_id' => '5','name' => 'Jashpur','status' => '1'),
            array('id' => '124','state_id' => '5','name' => 'Kabirdham','status' => '1'),
            array('id' => '125','state_id' => '5','name' => 'Uttar Bastar Kanker','status' => '1'),
            array('id' => '126','state_id' => '5','name' => 'Kondagaon','status' => '1'),
            array('id' => '127','state_id' => '5','name' => 'Korba','status' => '1'),
            array('id' => '128','state_id' => '5','name' => 'Koria','status' => '1'),
            array('id' => '129','state_id' => '5','name' => 'Mahasamund','status' => '1'),
            array('id' => '130','state_id' => '5','name' => 'Mungeli','status' => '1'),
            array('id' => '131','state_id' => '5','name' => 'Narayanpur','status' => '1'),
            array('id' => '132','state_id' => '5','name' => 'Raigarh','status' => '1'),
            array('id' => '133','state_id' => '5','name' => 'Raipur','status' => '1'),
            array('id' => '134','state_id' => '5','name' => 'Rajnandgaon','status' => '1'),
            array('id' => '135','state_id' => '5','name' => 'Sukma','status' => '1'),
            array('id' => '136','state_id' => '5','name' => 'Surajpur','status' => '1'),
            array('id' => '137','state_id' => '5','name' => 'Sarguja','status' => '1'),
            array('id' => '138','state_id' => '32','name' => 'Dadra and Nagar Haveli','status' => '1'),
            array('id' => '141','state_id' => '30','name' => 'Central Delhi','status' => '1'),
            array('id' => '142','state_id' => '30','name' => 'East Delhi','status' => '1'),
            array('id' => '143','state_id' => '30','name' => 'New Delhi','status' => '1'),
            array('id' => '144','state_id' => '30','name' => 'North Delhi','status' => '1'),
            array('id' => '145','state_id' => '30','name' => 'North East Delhi','status' => '1'),
            array('id' => '146','state_id' => '30','name' => 'North West Delhi','status' => '1'),
            array('id' => '147','state_id' => '30','name' => 'Shahdara','status' => '1'),
            array('id' => '148','state_id' => '30','name' => 'South Delhi','status' => '1'),
            array('id' => '149','state_id' => '30','name' => 'South East Delhi','status' => '1'),
            array('id' => '150','state_id' => '30','name' => 'South West Delhi','status' => '1'),
            array('id' => '151','state_id' => '30','name' => 'West Delhi','status' => '1'),
            array('id' => '152','state_id' => '6','name' => 'North Goa','status' => '1'),
            array('id' => '153','state_id' => '6','name' => 'South Goa','status' => '1'),
            array('id' => '154','state_id' => '7','name' => 'Ahmedabad','status' => '1'),
            array('id' => '155','state_id' => '7','name' => 'Amreli','status' => '1'),
            array('id' => '156','state_id' => '7','name' => 'Anand','status' => '1'),
            array('id' => '157','state_id' => '7','name' => 'Arvalli','status' => '1'),
            array('id' => '158','state_id' => '7','name' => 'Banaskantha','status' => '1'),
            array('id' => '159','state_id' => '7','name' => 'Bharuch','status' => '1'),
            array('id' => '160','state_id' => '7','name' => 'Bhavnagar','status' => '1'),
            array('id' => '161','state_id' => '7','name' => 'Botad','status' => '1'),
            array('id' => '162','state_id' => '7','name' => 'Chhotaudepur','status' => '1'),
            array('id' => '163','state_id' => '7','name' => 'Dahod','status' => '1'),
            array('id' => '164','state_id' => '7','name' => 'Dangs','status' => '1'),
            array('id' => '165','state_id' => '7','name' => 'Devbhumi Dwarka','status' => '1'),
            array('id' => '166','state_id' => '7','name' => 'Gandhinagar','status' => '1'),
            array('id' => '167','state_id' => '7','name' => 'Gir Somnath','status' => '1'),
            array('id' => '168','state_id' => '7','name' => 'Jamnagar','status' => '1'),
            array('id' => '169','state_id' => '7','name' => 'Junagadh','status' => '1'),
            array('id' => '170','state_id' => '7','name' => 'Kheda','status' => '1'),
            array('id' => '171','state_id' => '7','name' => 'Kachchh','status' => '1'),
            array('id' => '172','state_id' => '7','name' => 'Mahisagar','status' => '1'),
            array('id' => '173','state_id' => '7','name' => 'Mahesana','status' => '1'),
            array('id' => '174','state_id' => '7','name' => 'Morbi','status' => '1'),
            array('id' => '175','state_id' => '7','name' => 'Narmada','status' => '1'),
            array('id' => '176','state_id' => '7','name' => 'Navsari','status' => '1'),
            array('id' => '177','state_id' => '7','name' => 'Panchmahal','status' => '1'),
            array('id' => '178','state_id' => '7','name' => 'Patan','status' => '1'),
            array('id' => '179','state_id' => '7','name' => 'Porbandar','status' => '1'),
            array('id' => '180','state_id' => '7','name' => 'Rajkot','status' => '1'),
            array('id' => '181','state_id' => '7','name' => 'Sabarkantha','status' => '1'),
            array('id' => '182','state_id' => '7','name' => 'Surat','status' => '1'),
            array('id' => '183','state_id' => '7','name' => 'Surendranagar','status' => '1'),
            array('id' => '184','state_id' => '7','name' => 'Tapi','status' => '1'),
            array('id' => '185','state_id' => '7','name' => 'Vadodara','status' => '1'),
            array('id' => '186','state_id' => '7','name' => 'Valsad','status' => '1'),
            array('id' => '187','state_id' => '8','name' => 'Ambala','status' => '1'),
            array('id' => '188','state_id' => '8','name' => 'Bhiwani','status' => '1'),
            array('id' => '189','state_id' => '8','name' => 'Charkhi Dadri','status' => '1'),
            array('id' => '190','state_id' => '8','name' => 'Faridabad','status' => '1'),
            array('id' => '191','state_id' => '8','name' => 'Fatehabad','status' => '1'),
            array('id' => '192','state_id' => '8','name' => 'Gurgaon','status' => '1'),
            array('id' => '193','state_id' => '8','name' => 'Hissar','status' => '1'),
            array('id' => '194','state_id' => '8','name' => 'Jhajjar','status' => '1'),
            array('id' => '195','state_id' => '8','name' => 'Jind','status' => '1'),
            array('id' => '196','state_id' => '8','name' => 'Kaithal','status' => '1'),
            array('id' => '197','state_id' => '8','name' => 'Karnal','status' => '1'),
            array('id' => '198','state_id' => '8','name' => 'Kurukshetra','status' => '1'),
            array('id' => '199','state_id' => '8','name' => 'Mahendragarh','status' => '1'),
            array('id' => '200','state_id' => '8','name' => 'Mewat','status' => '1'),
            array('id' => '201','state_id' => '8','name' => 'Palwal','status' => '1'),
            array('id' => '202','state_id' => '8','name' => 'Panchkula','status' => '1'),
            array('id' => '203','state_id' => '8','name' => 'Panipat','status' => '1'),
            array('id' => '204','state_id' => '8','name' => 'Rewari','status' => '1'),
            array('id' => '205','state_id' => '8','name' => 'Rohtak','status' => '1'),
            array('id' => '206','state_id' => '8','name' => 'Sirsa','status' => '1'),
            array('id' => '207','state_id' => '8','name' => 'Sonipat','status' => '1'),
            array('id' => '208','state_id' => '8','name' => 'Yamunanagar','status' => '1'),
            array('id' => '210','state_id' => '9','name' => 'Chamba','status' => '1'),
            array('id' => '211','state_id' => '9','name' => 'Hamirpur','status' => '1'),
            array('id' => '212','state_id' => '9','name' => 'Kangra','status' => '1'),
            array('id' => '213','state_id' => '9','name' => 'Kinnaur','status' => '1'),
            array('id' => '214','state_id' => '9','name' => 'Kullu','status' => '1'),
            array('id' => '215','state_id' => '9','name' => 'Lahaul & Spiti','status' => '1'),
            array('id' => '216','state_id' => '9','name' => 'Mandi','status' => '1'),
            array('id' => '217','state_id' => '9','name' => 'Shimla','status' => '1'),
            array('id' => '218','state_id' => '9','name' => 'Sirmour','status' => '1'),
            array('id' => '219','state_id' => '9','name' => 'Solan','status' => '1'),
            array('id' => '220','state_id' => '9','name' => 'Una','status' => '1'),
            array('id' => '221','state_id' => '10','name' => 'Anantnag','status' => '1'),
            array('id' => '222','state_id' => '10','name' => 'Bandipur','status' => '1'),
            array('id' => '223','state_id' => '10','name' => 'Baramula','status' => '1'),
            array('id' => '225','state_id' => '10','name' => 'Doda','status' => '1'),
            array('id' => '226','state_id' => '10','name' => 'Ganderbal','status' => '1'),
            array('id' => '227','state_id' => '10','name' => 'Jammu','status' => '1'),
            array('id' => '229','state_id' => '10','name' => 'Kathua','status' => '1'),
            array('id' => '230','state_id' => '10','name' => 'Kishtwar','status' => '1'),
            array('id' => '231','state_id' => '10','name' => 'Kulgam','status' => '1'),
            array('id' => '232','state_id' => '10','name' => 'Kupwara','status' => '1'),
            array('id' => '234','state_id' => '10','name' => 'Poonch','status' => '1'),
            array('id' => '235','state_id' => '10','name' => 'Pulwama','status' => '1'),
            array('id' => '236','state_id' => '10','name' => 'Rajauri','status' => '1'),
            array('id' => '237','state_id' => '10','name' => 'Ramban','status' => '1'),
            array('id' => '238','state_id' => '10','name' => 'Reasi','status' => '1'),
            array('id' => '239','state_id' => '10','name' => 'Samba','status' => '1'),
            array('id' => '240','state_id' => '10','name' => 'Shopian','status' => '1'),
            array('id' => '241','state_id' => '10','name' => 'Srinagar','status' => '1'),
            array('id' => '242','state_id' => '10','name' => 'Udhampur','status' => '1'),
            array('id' => '243','state_id' => '11','name' => 'Bokaro','status' => '1'),
            array('id' => '244','state_id' => '11','name' => 'Chatra','status' => '1'),
            array('id' => '245','state_id' => '11','name' => 'Deoghar','status' => '1'),
            array('id' => '246','state_id' => '11','name' => 'Dhanbad','status' => '1'),
            array('id' => '247','state_id' => '11','name' => 'Dumka','status' => '1'),
            array('id' => '248','state_id' => '11','name' => 'East Singhbhum','status' => '1'),
            array('id' => '249','state_id' => '11','name' => 'Garhwa','status' => '1'),
            array('id' => '250','state_id' => '11','name' => 'Giridih','status' => '1'),
            array('id' => '251','state_id' => '11','name' => 'Godda','status' => '1'),
            array('id' => '252','state_id' => '11','name' => 'Gumla','status' => '1'),
            array('id' => '253','state_id' => '11','name' => 'Hazaribagh','status' => '1'),
            array('id' => '254','state_id' => '11','name' => 'Jamtara','status' => '1'),
            array('id' => '255','state_id' => '11','name' => 'Khunti','status' => '1'),
            array('id' => '256','state_id' => '11','name' => 'Koderma','status' => '1'),
            array('id' => '257','state_id' => '11','name' => 'Latehar','status' => '1'),
            array('id' => '258','state_id' => '11','name' => 'Lohardaga','status' => '1'),
            array('id' => '259','state_id' => '11','name' => 'Pakur','status' => '1'),
            array('id' => '260','state_id' => '11','name' => 'Palamu','status' => '1'),
            array('id' => '261','state_id' => '11','name' => 'Ramgarh','status' => '1'),
            array('id' => '262','state_id' => '11','name' => 'Ranchi','status' => '1'),
            array('id' => '263','state_id' => '11','name' => 'Sahebganj','status' => '1'),
            array('id' => '264','state_id' => '11','name' => 'Seraikela Kharsawan','status' => '1'),
            array('id' => '265','state_id' => '11','name' => 'Simdega','status' => '1'),
            array('id' => '266','state_id' => '11','name' => 'West Singhbhum','status' => '1'),
            array('id' => '267','state_id' => '12','name' => 'Bagalkot','status' => '1'),
            array('id' => '268','state_id' => '12','name' => 'Bellary','status' => '1'),
            array('id' => '269','state_id' => '12','name' => 'Belagavi','status' => '1'),
            array('id' => '270','state_id' => '12','name' => 'Bangalore Rural','status' => '1'),
            array('id' => '271','state_id' => '12','name' => 'Bangalore Urban','status' => '1'),
            array('id' => '272','state_id' => '12','name' => 'Bidar','status' => '1'),
            array('id' => '273','state_id' => '12','name' => 'Chamarajnagar','status' => '1'),
            array('id' => '274','state_id' => '12','name' => 'Chikkaballapur','status' => '1'),
            array('id' => '275','state_id' => '12','name' => 'Chikmagalur','status' => '1'),
            array('id' => '276','state_id' => '12','name' => 'Chitradurga','status' => '1'),
            array('id' => '277','state_id' => '12','name' => 'Dakshina Kannada','status' => '1'),
            array('id' => '278','state_id' => '12','name' => 'Davangere','status' => '1'),
            array('id' => '279','state_id' => '12','name' => 'Dharwad','status' => '1'),
            array('id' => '280','state_id' => '12','name' => 'Gadag','status' => '1'),
            array('id' => '281','state_id' => '12','name' => 'Hassan','status' => '1'),
            array('id' => '282','state_id' => '12','name' => 'Haveri','status' => '1'),
            array('id' => '284','state_id' => '12','name' => 'Kodagu','status' => '1'),
            array('id' => '285','state_id' => '12','name' => 'Kolar','status' => '1'),
            array('id' => '286','state_id' => '12','name' => 'Koppal','status' => '1'),
            array('id' => '287','state_id' => '12','name' => 'Mandya','status' => '1'),
            array('id' => '288','state_id' => '12','name' => 'Mysore','status' => '1'),
            array('id' => '289','state_id' => '12','name' => 'Raichur','status' => '1'),
            array('id' => '290','state_id' => '12','name' => 'Ramanagara','status' => '1'),
            array('id' => '291','state_id' => '12','name' => 'Shimoga','status' => '1'),
            array('id' => '292','state_id' => '12','name' => 'Tumkur','status' => '1'),
            array('id' => '293','state_id' => '12','name' => 'Udupi','status' => '1'),
            array('id' => '294','state_id' => '12','name' => 'Uttara Kannada','status' => '1'),
            array('id' => '296','state_id' => '12','name' => 'Yadgir','status' => '1'),
            array('id' => '297','state_id' => '13','name' => 'Alappuzha','status' => '1'),
            array('id' => '298','state_id' => '13','name' => 'Ernakulam','status' => '1'),
            array('id' => '299','state_id' => '13','name' => 'Idukki','status' => '1'),
            array('id' => '300','state_id' => '13','name' => 'Kannur','status' => '1'),
            array('id' => '301','state_id' => '13','name' => 'Kasaragod','status' => '1'),
            array('id' => '302','state_id' => '13','name' => 'Kollam','status' => '1'),
            array('id' => '303','state_id' => '13','name' => 'Kottayam','status' => '1'),
            array('id' => '304','state_id' => '13','name' => 'Kozhikode','status' => '1'),
            array('id' => '305','state_id' => '13','name' => 'Malappuram','status' => '1'),
            array('id' => '306','state_id' => '13','name' => 'Palakkad','status' => '1'),
            array('id' => '307','state_id' => '13','name' => 'Pathanamthitta','status' => '1'),
            array('id' => '308','state_id' => '13','name' => 'Thrissur','status' => '1'),
            array('id' => '309','state_id' => '13','name' => 'Thiruvananthapuram','status' => '1'),
            array('id' => '310','state_id' => '13','name' => 'Wayanad','status' => '1'),
            array('id' => '311','state_id' => '36','name' => 'Lakshadweep','status' => '1'),
            array('id' => '312','state_id' => '14','name' => 'Agar Malwa','status' => '1'),
            array('id' => '313','state_id' => '14','name' => 'Alirajpur','status' => '1'),
            array('id' => '314','state_id' => '14','name' => 'Anuppur','status' => '1'),
            array('id' => '315','state_id' => '14','name' => 'Ashok Nagar','status' => '1'),
            array('id' => '316','state_id' => '14','name' => 'Balaghat','status' => '1'),
            array('id' => '317','state_id' => '14','name' => 'Barwani','status' => '1'),
            array('id' => '318','state_id' => '14','name' => 'Betul','status' => '1'),
            array('id' => '319','state_id' => '14','name' => 'Bhind','status' => '1'),
            array('id' => '320','state_id' => '14','name' => 'Bhopal','status' => '1'),
            array('id' => '321','state_id' => '14','name' => 'Burhanpur','status' => '1'),
            array('id' => '322','state_id' => '14','name' => 'Chhatarpur','status' => '1'),
            array('id' => '323','state_id' => '14','name' => 'Chhindwara','status' => '1'),
            array('id' => '324','state_id' => '14','name' => 'Damoh','status' => '1'),
            array('id' => '325','state_id' => '14','name' => 'Datia','status' => '1'),
            array('id' => '326','state_id' => '14','name' => 'Dewas','status' => '1'),
            array('id' => '327','state_id' => '14','name' => 'Dhar','status' => '1'),
            array('id' => '328','state_id' => '14','name' => 'Dindori','status' => '1'),
            array('id' => '329','state_id' => '14','name' => 'Guna','status' => '1'),
            array('id' => '330','state_id' => '14','name' => 'Gwalior','status' => '1'),
            array('id' => '331','state_id' => '14','name' => 'Harda','status' => '1'),
            array('id' => '332','state_id' => '14','name' => 'Narmadapuram','status' => '1'),
            array('id' => '333','state_id' => '14','name' => 'Indore','status' => '1'),
            array('id' => '334','state_id' => '14','name' => 'Jabalpur','status' => '1'),
            array('id' => '335','state_id' => '14','name' => 'Jhabua','status' => '1'),
            array('id' => '336','state_id' => '14','name' => 'Katni','status' => '1'),
            array('id' => '337','state_id' => '14','name' => 'Khandwa(East Nimar)','status' => '1'),
            array('id' => '338','state_id' => '14','name' => 'Khargone(West Nimar)','status' => '1'),
            array('id' => '339','state_id' => '14','name' => 'Mandla','status' => '1'),
            array('id' => '340','state_id' => '14','name' => 'Mandsaur','status' => '1'),
            array('id' => '341','state_id' => '14','name' => 'Morena','status' => '1'),
            array('id' => '342','state_id' => '14','name' => 'Narsinghpur','status' => '1'),
            array('id' => '343','state_id' => '14','name' => 'Neemuch','status' => '1'),
            array('id' => '344','state_id' => '14','name' => 'Panna','status' => '1'),
            array('id' => '345','state_id' => '14','name' => 'Raisen','status' => '1'),
            array('id' => '346','state_id' => '14','name' => 'Rajgarh','status' => '1'),
            array('id' => '347','state_id' => '14','name' => 'Ratlam','status' => '1'),
            array('id' => '348','state_id' => '14','name' => 'Rewa','status' => '1'),
            array('id' => '349','state_id' => '14','name' => 'Sagar','status' => '1'),
            array('id' => '350','state_id' => '14','name' => 'Satna','status' => '1'),
            array('id' => '351','state_id' => '14','name' => 'Sehore','status' => '1'),
            array('id' => '352','state_id' => '14','name' => 'Seoni','status' => '1'),
            array('id' => '353','state_id' => '14','name' => 'Shahdol','status' => '1'),
            array('id' => '354','state_id' => '14','name' => 'Shajapur','status' => '1'),
            array('id' => '355','state_id' => '14','name' => 'Sheopur','status' => '1'),
            array('id' => '356','state_id' => '14','name' => 'Shivpuri','status' => '1'),
            array('id' => '357','state_id' => '14','name' => 'Sidhi','status' => '1'),
            array('id' => '358','state_id' => '14','name' => 'Singrauli','status' => '1'),
            array('id' => '359','state_id' => '14','name' => 'Tikamgarh','status' => '1'),
            array('id' => '360','state_id' => '14','name' => 'Ujjain','status' => '1'),
            array('id' => '361','state_id' => '14','name' => 'Umaria','status' => '1'),
            array('id' => '362','state_id' => '14','name' => 'Vidisha','status' => '1'),
            array('id' => '363','state_id' => '15','name' => 'Ahmednagar','status' => '1'),
            array('id' => '364','state_id' => '15','name' => 'Akola','status' => '1'),
            array('id' => '365','state_id' => '15','name' => 'Amravati','status' => '1'),
            array('id' => '367','state_id' => '15','name' => 'Beed','status' => '1'),
            array('id' => '368','state_id' => '15','name' => 'Bhandara','status' => '1'),
            array('id' => '369','state_id' => '15','name' => 'Buldhana','status' => '1'),
            array('id' => '370','state_id' => '15','name' => 'Chandrapur','status' => '1'),
            array('id' => '371','state_id' => '15','name' => 'Dhule','status' => '1'),
            array('id' => '372','state_id' => '15','name' => 'Gadchiroli','status' => '1'),
            array('id' => '373','state_id' => '15','name' => 'Gondiya','status' => '1'),
            array('id' => '374','state_id' => '15','name' => 'Hingoli','status' => '1'),
            array('id' => '375','state_id' => '15','name' => 'Jalgaon','status' => '1'),
            array('id' => '376','state_id' => '15','name' => 'Jalna','status' => '1'),
            array('id' => '377','state_id' => '15','name' => 'Kolhapur','status' => '1'),
            array('id' => '378','state_id' => '15','name' => 'Latur','status' => '1'),
            array('id' => '379','state_id' => '15','name' => 'Mumbai City','status' => '1'),
            array('id' => '380','state_id' => '15','name' => 'Mumbai Suburban','status' => '1'),
            array('id' => '381','state_id' => '15','name' => 'Nanded','status' => '1'),
            array('id' => '382','state_id' => '15','name' => 'Nandurbar','status' => '1'),
            array('id' => '383','state_id' => '15','name' => 'Nagpur','status' => '1'),
            array('id' => '384','state_id' => '15','name' => 'Nashik','status' => '1'),
            array('id' => '385','state_id' => '15','name' => 'Dharashiv','status' => '1'),
            array('id' => '386','state_id' => '15','name' => 'Palghar','status' => '1'),
            array('id' => '387','state_id' => '15','name' => 'Parbhani','status' => '1'),
            array('id' => '388','state_id' => '15','name' => 'Pune','status' => '1'),
            array('id' => '389','state_id' => '15','name' => 'Raigad','status' => '1'),
            array('id' => '390','state_id' => '15','name' => 'Ratnagiri','status' => '1'),
            array('id' => '391','state_id' => '15','name' => 'Sangli','status' => '1'),
            array('id' => '392','state_id' => '15','name' => 'Satara','status' => '1'),
            array('id' => '393','state_id' => '15','name' => 'Sindhudurg','status' => '1'),
            array('id' => '394','state_id' => '15','name' => 'Solapur','status' => '1'),
            array('id' => '395','state_id' => '15','name' => 'Thane','status' => '1'),
            array('id' => '396','state_id' => '15','name' => 'Wardha','status' => '1'),
            array('id' => '397','state_id' => '15','name' => 'Washim','status' => '1'),
            array('id' => '398','state_id' => '15','name' => 'Yavatmal','status' => '1'),
            array('id' => '399','state_id' => '16','name' => 'Bishnupur','status' => '1'),
            array('id' => '400','state_id' => '16','name' => 'Thoubal','status' => '1'),
            array('id' => '401','state_id' => '16','name' => 'Imphal East','status' => '1'),
            array('id' => '402','state_id' => '16','name' => 'Imphal West','status' => '1'),
            array('id' => '403','state_id' => '16','name' => 'Senapati','status' => '1'),
            array('id' => '404','state_id' => '16','name' => 'Ukhrul','status' => '1'),
            array('id' => '405','state_id' => '16','name' => 'Chandel','status' => '1'),
            array('id' => '406','state_id' => '16','name' => 'Churachandpur','status' => '1'),
            array('id' => '407','state_id' => '16','name' => 'Tamenglong','status' => '1'),
            array('id' => '408','state_id' => '16','name' => 'Jiribam','status' => '1'),
            array('id' => '410','state_id' => '16','name' => 'Kakching','status' => '1'),
            array('id' => '411','state_id' => '16','name' => 'Tengnoupal','status' => '1'),
            array('id' => '412','state_id' => '16','name' => 'Kamjong','status' => '1'),
            array('id' => '414','state_id' => '16','name' => 'Pherzawl','status' => '1'),
            array('id' => '415','state_id' => '17','name' => 'East Garo Hills','status' => '1'),
            array('id' => '416','state_id' => '17','name' => 'East Khasi Hills','status' => '1'),
            array('id' => '417','state_id' => '17','name' => 'East Jaintia Hills','status' => '1'),
            array('id' => '418','state_id' => '17','name' => 'North Garo Hills','status' => '1'),
            array('id' => '419','state_id' => '17','name' => 'RI-BHOI','status' => '1'),
            array('id' => '420','state_id' => '17','name' => 'South Garo Hills','status' => '1'),
            array('id' => '421','state_id' => '17','name' => 'South West Garo Hills','status' => '1'),
            array('id' => '422','state_id' => '17','name' => 'South West Khasi Hills','status' => '1'),
            array('id' => '423','state_id' => '17','name' => 'West Jaintia Hills','status' => '1'),
            array('id' => '424','state_id' => '17','name' => 'West Garo Hills','status' => '1'),
            array('id' => '425','state_id' => '17','name' => 'West Khasi Hills','status' => '1'),
            array('id' => '426','state_id' => '18','name' => 'Aizawl','status' => '1'),
            array('id' => '427','state_id' => '18','name' => 'Champhai','status' => '1'),
            array('id' => '428','state_id' => '18','name' => 'Kolasib','status' => '1'),
            array('id' => '429','state_id' => '18','name' => 'Lawngtlai','status' => '1'),
            array('id' => '430','state_id' => '18','name' => 'Lunglei','status' => '1'),
            array('id' => '431','state_id' => '18','name' => 'Mamit','status' => '1'),
            array('id' => '432','state_id' => '18','name' => 'Siaha','status' => '1'),
            array('id' => '433','state_id' => '18','name' => 'Serchhip','status' => '1'),
            array('id' => '434','state_id' => '19','name' => 'Dimapur','status' => '1'),
            array('id' => '435','state_id' => '19','name' => 'Kiphire','status' => '1'),
            array('id' => '436','state_id' => '19','name' => 'Kohima','status' => '1'),
            array('id' => '437','state_id' => '19','name' => 'Longleng','status' => '1'),
            array('id' => '438','state_id' => '19','name' => 'Mokokchung','status' => '1'),
            array('id' => '439','state_id' => '19','name' => 'Mon','status' => '1'),
            array('id' => '440','state_id' => '19','name' => 'Peren','status' => '1'),
            array('id' => '441','state_id' => '19','name' => 'Phek','status' => '1'),
            array('id' => '442','state_id' => '19','name' => 'Tuensang','status' => '1'),
            array('id' => '443','state_id' => '19','name' => 'Wokha','status' => '1'),
            array('id' => '444','state_id' => '19','name' => 'Zunheboto','status' => '1'),
            array('id' => '445','state_id' => '20','name' => 'Angul','status' => '1'),
            array('id' => '447','state_id' => '20','name' => 'Bhadrak','status' => '1'),
            array('id' => '449','state_id' => '20','name' => 'Bargarh','status' => '1'),
            array('id' => '450','state_id' => '20','name' => 'Balasore','status' => '1'),
            array('id' => '451','state_id' => '20','name' => 'Cuttack','status' => '1'),
            array('id' => '453','state_id' => '20','name' => 'Dhenkanal','status' => '1'),
            array('id' => '454','state_id' => '20','name' => 'Ganjam','status' => '1'),
            array('id' => '455','state_id' => '20','name' => 'Gajapati','status' => '1'),
            array('id' => '456','state_id' => '20','name' => 'Jharsuguda','status' => '1'),
            array('id' => '457','state_id' => '20','name' => 'Jajpur','status' => '1'),
            array('id' => '458','state_id' => '20','name' => 'Jagatsinghpur','status' => '1'),
            array('id' => '461','state_id' => '20','name' => 'Kalahandi','status' => '1'),
            array('id' => '462','state_id' => '20','name' => 'Kandhamal','status' => '1'),
            array('id' => '463','state_id' => '20','name' => 'Koraput','status' => '1'),
            array('id' => '464','state_id' => '20','name' => 'Kendrapara','status' => '1'),
            array('id' => '465','state_id' => '20','name' => 'Malkangiri','status' => '1'),
            array('id' => '466','state_id' => '20','name' => 'Mayurbhanj','status' => '1'),
            array('id' => '467','state_id' => '20','name' => 'Nabarangpur','status' => '1'),
            array('id' => '468','state_id' => '20','name' => 'Nuapada','status' => '1'),
            array('id' => '469','state_id' => '20','name' => 'Nayagarh','status' => '1'),
            array('id' => '470','state_id' => '20','name' => 'Puri','status' => '1'),
            array('id' => '471','state_id' => '20','name' => 'Rayagada','status' => '1'),
            array('id' => '472','state_id' => '20','name' => 'Sambalpur','status' => '1'),
            array('id' => '473','state_id' => '20','name' => 'Subarnapur','status' => '1'),
            array('id' => '474','state_id' => '20','name' => 'Sundargarh','status' => '1'),
            array('id' => '475','state_id' => '31','name' => 'Karaikal','status' => '1'),
            array('id' => '476','state_id' => '31','name' => 'Mahe','status' => '1'),
            array('id' => '477','state_id' => '31','name' => 'Puducherry','status' => '1'),
            array('id' => '478','state_id' => '31','name' => 'Yanam','status' => '1'),
            array('id' => '479','state_id' => '21','name' => 'Amritsar','status' => '1'),
            array('id' => '480','state_id' => '21','name' => 'Barnala','status' => '1'),
            array('id' => '481','state_id' => '21','name' => 'Bathinda','status' => '1'),
            array('id' => '482','state_id' => '21','name' => 'Firozpur','status' => '1'),
            array('id' => '483','state_id' => '21','name' => 'Faridkot','status' => '1'),
            array('id' => '484','state_id' => '21','name' => 'Fatehgarh Sahib','status' => '1'),
            array('id' => '485','state_id' => '21','name' => 'Fazilka','status' => '1'),
            array('id' => '486','state_id' => '21','name' => 'Gurdaspur','status' => '1'),
            array('id' => '487','state_id' => '21','name' => 'Hoshiarpur','status' => '1'),
            array('id' => '488','state_id' => '21','name' => 'Jalandhar','status' => '1'),
            array('id' => '489','state_id' => '21','name' => 'Kapurthala','status' => '1'),
            array('id' => '490','state_id' => '21','name' => 'Ludhiana','status' => '1'),
            array('id' => '491','state_id' => '21','name' => 'Mansa','status' => '1'),
            array('id' => '492','state_id' => '21','name' => 'Moga','status' => '1'),
            array('id' => '493','state_id' => '21','name' => 'Sri Muktsar Sahib','status' => '1'),
            array('id' => '494','state_id' => '21','name' => 'Pathankot','status' => '1'),
            array('id' => '495','state_id' => '21','name' => 'Patiala','status' => '1'),
            array('id' => '496','state_id' => '21','name' => 'Rupnagar','status' => '1'),
            array('id' => '497','state_id' => '21','name' => 'Sahibzada Ajit Singh Nagar','status' => '1'),
            array('id' => '498','state_id' => '21','name' => 'Sangrur','status' => '1'),
            array('id' => '499','state_id' => '21','name' => 'Shahid Bhagat Singh Nagar','status' => '1'),
            array('id' => '500','state_id' => '21','name' => 'Tarn Taran','status' => '1'),
            array('id' => '501','state_id' => '22','name' => 'Ajmer','status' => '1'),
            array('id' => '502','state_id' => '22','name' => 'Alwar','status' => '1'),
            array('id' => '503','state_id' => '22','name' => 'Bikaner','status' => '1'),
            array('id' => '504','state_id' => '22','name' => 'Barmer','status' => '1'),
            array('id' => '505','state_id' => '22','name' => 'Banswara','status' => '1'),
            array('id' => '506','state_id' => '22','name' => 'Bharatpur','status' => '1'),
            array('id' => '507','state_id' => '22','name' => 'Baran','status' => '1'),
            array('id' => '508','state_id' => '22','name' => 'Bundi','status' => '1'),
            array('id' => '509','state_id' => '22','name' => 'Bhilwara','status' => '1'),
            array('id' => '510','state_id' => '22','name' => 'Churu','status' => '1'),
            array('id' => '511','state_id' => '22','name' => 'Chittorgarh','status' => '1'),
            array('id' => '512','state_id' => '22','name' => 'Dausa','status' => '1'),
            array('id' => '513','state_id' => '22','name' => 'Dholpur','status' => '1'),
            array('id' => '514','state_id' => '22','name' => 'Dungarpur','status' => '1'),
            array('id' => '515','state_id' => '22','name' => 'Ganganagar','status' => '1'),
            array('id' => '516','state_id' => '22','name' => 'Hanumangarh','status' => '1'),
            array('id' => '517','state_id' => '22','name' => 'Jhunjhunu','status' => '1'),
            array('id' => '518','state_id' => '22','name' => 'Jalore','status' => '1'),
            array('id' => '519','state_id' => '22','name' => 'Jodhpur','status' => '1'),
            array('id' => '520','state_id' => '22','name' => 'Jaipur','status' => '1'),
            array('id' => '521','state_id' => '22','name' => 'Jaisalmer','status' => '1'),
            array('id' => '522','state_id' => '22','name' => 'Jhalawar','status' => '1'),
            array('id' => '523','state_id' => '22','name' => 'Karauli','status' => '1'),
            array('id' => '524','state_id' => '22','name' => 'Kota','status' => '1'),
            array('id' => '525','state_id' => '22','name' => 'Nagaur','status' => '1'),
            array('id' => '526','state_id' => '22','name' => 'Pali','status' => '1'),
            array('id' => '527','state_id' => '22','name' => 'Pratapgarh','status' => '1'),
            array('id' => '528','state_id' => '22','name' => 'Rajsamand','status' => '1'),
            array('id' => '529','state_id' => '22','name' => 'Sikar','status' => '1'),
            array('id' => '530','state_id' => '22','name' => 'Sawai Madhopur','status' => '1'),
            array('id' => '531','state_id' => '22','name' => 'Sirohi','status' => '1'),
            array('id' => '532','state_id' => '22','name' => 'Tonk','status' => '1'),
            array('id' => '533','state_id' => '22','name' => 'Udaipur','status' => '1'),
            array('id' => '534','state_id' => '23','name' => 'Gangtok','status' => '1'),
            array('id' => '535','state_id' => '23','name' => 'Mangan','status' => '1'),
            array('id' => '536','state_id' => '23','name' => 'Namchi','status' => '1'),
            array('id' => '537','state_id' => '23','name' => 'Soreng','status' => '1'),
            array('id' => '538','state_id' => '24','name' => 'Ariyalur','status' => '1'),
            array('id' => '539','state_id' => '24','name' => 'Chennai','status' => '1'),
            array('id' => '540','state_id' => '24','name' => 'Coimbatore','status' => '1'),
            array('id' => '541','state_id' => '24','name' => 'Cuddalore','status' => '1'),
            array('id' => '542','state_id' => '24','name' => 'Dharmapuri','status' => '1'),
            array('id' => '543','state_id' => '24','name' => 'Dindigul','status' => '1'),
            array('id' => '544','state_id' => '24','name' => 'Erode','status' => '1'),
            array('id' => '545','state_id' => '24','name' => 'Kancheepuram','status' => '1'),
            array('id' => '546','state_id' => '24','name' => 'Kanniyakumari','status' => '1'),
            array('id' => '547','state_id' => '24','name' => 'Karur','status' => '1'),
            array('id' => '548','state_id' => '24','name' => 'Krishnagiri','status' => '1'),
            array('id' => '549','state_id' => '24','name' => 'Madurai','status' => '1'),
            array('id' => '550','state_id' => '24','name' => 'Nagapattinam','status' => '1'),
            array('id' => '551','state_id' => '24','name' => 'The Nilgiris','status' => '1'),
            array('id' => '552','state_id' => '24','name' => 'Namakkal','status' => '1'),
            array('id' => '553','state_id' => '24','name' => 'Perambalur','status' => '1'),
            array('id' => '554','state_id' => '24','name' => 'Pudukkottai','status' => '1'),
            array('id' => '555','state_id' => '24','name' => 'Ramanathapuram','status' => '1'),
            array('id' => '556','state_id' => '24','name' => 'Salem','status' => '1'),
            array('id' => '557','state_id' => '24','name' => 'Sivaganga','status' => '1'),
            array('id' => '558','state_id' => '24','name' => 'Tiruppur','status' => '1'),
            array('id' => '559','state_id' => '24','name' => 'Tiruchirappalli','status' => '1'),
            array('id' => '560','state_id' => '24','name' => 'Theni','status' => '1'),
            array('id' => '561','state_id' => '24','name' => 'Tirunelveli','status' => '1'),
            array('id' => '562','state_id' => '24','name' => 'Thanjavur','status' => '1'),
            array('id' => '563','state_id' => '24','name' => 'Thoothukudi','status' => '1'),
            array('id' => '564','state_id' => '24','name' => 'Thiruvallur','status' => '1'),
            array('id' => '565','state_id' => '24','name' => 'Thiruvarur','status' => '1'),
            array('id' => '566','state_id' => '24','name' => 'Tiruvannamalai','status' => '1'),
            array('id' => '567','state_id' => '24','name' => 'Vellore','status' => '1'),
            array('id' => '568','state_id' => '24','name' => 'Viluppuram','status' => '1'),
            array('id' => '569','state_id' => '24','name' => 'Virudhunagar','status' => '1'),
            array('id' => '570','state_id' => '25','name' => 'Adilabad','status' => '1'),
            array('id' => '571','state_id' => '25','name' => 'Komaram Bheem Asifabad','status' => '1'),
            array('id' => '572','state_id' => '25','name' => 'Bhadradri Kothagudem','status' => '1'),
            array('id' => '573','state_id' => '25','name' => 'Hyderabad','status' => '1'),
            array('id' => '574','state_id' => '25','name' => 'Jagtial','status' => '1'),
            array('id' => '575','state_id' => '25','name' => 'Jangaon','status' => '1'),
            array('id' => '576','state_id' => '25','name' => 'Jayashankar Bhupalpalle','status' => '1'),
            array('id' => '577','state_id' => '25','name' => 'Jogulamba Gadwal','status' => '1'),
            array('id' => '578','state_id' => '25','name' => 'Kamareddy','status' => '1'),
            array('id' => '579','state_id' => '25','name' => 'Karimnagar','status' => '1'),
            array('id' => '580','state_id' => '25','name' => 'Khammam','status' => '1'),
            array('id' => '581','state_id' => '25','name' => 'Mahabubabad','status' => '1'),
            array('id' => '582','state_id' => '25','name' => 'Mahbubnagar','status' => '1'),
            array('id' => '583','state_id' => '25','name' => 'Mancherial','status' => '1'),
            array('id' => '584','state_id' => '25','name' => 'Medak','status' => '1'),
            array('id' => '585','state_id' => '25','name' => 'Medchal Malkajgiri','status' => '1'),
            array('id' => '586','state_id' => '25','name' => 'Nalgonda','status' => '1'),
            array('id' => '587','state_id' => '25','name' => 'Nagarkurnool','status' => '1'),
            array('id' => '588','state_id' => '25','name' => 'Nirmal','status' => '1'),
            array('id' => '589','state_id' => '25','name' => 'Nizamabad','status' => '1'),
            array('id' => '590','state_id' => '25','name' => 'Peddapalli','status' => '1'),
            array('id' => '591','state_id' => '25','name' => 'Rajanna Sircilla','status' => '1'),
            array('id' => '592','state_id' => '25','name' => 'Ranga Reddy','status' => '1'),
            array('id' => '593','state_id' => '25','name' => 'Sangareddy','status' => '1'),
            array('id' => '594','state_id' => '25','name' => 'Siddipet','status' => '1'),
            array('id' => '595','state_id' => '25','name' => 'Suryapet','status' => '1'),
            array('id' => '596','state_id' => '25','name' => 'Vikarabad','status' => '1'),
            array('id' => '597','state_id' => '25','name' => 'Wanaparthy','status' => '1'),
            array('id' => '598','state_id' => '25','name' => 'Hanumakonda','status' => '1'),
            array('id' => '599','state_id' => '25','name' => 'Warangal','status' => '1'),
            array('id' => '600','state_id' => '25','name' => 'Yadadri Bhuvanagiri','status' => '1'),
            array('id' => '601','state_id' => '26','name' => 'Dhalai','status' => '1'),
            array('id' => '602','state_id' => '26','name' => 'Gomati','status' => '1'),
            array('id' => '603','state_id' => '26','name' => 'Khowai','status' => '1'),
            array('id' => '604','state_id' => '26','name' => 'North Tripura','status' => '1'),
            array('id' => '605','state_id' => '26','name' => 'Sepahijala','status' => '1'),
            array('id' => '606','state_id' => '26','name' => 'South Tripura','status' => '1'),
            array('id' => '607','state_id' => '26','name' => 'Unakoti','status' => '1'),
            array('id' => '608','state_id' => '26','name' => 'West Tripura','status' => '1'),
            array('id' => '609','state_id' => '28','name' => 'Agra','status' => '1'),
            array('id' => '610','state_id' => '28','name' => 'Aligarh','status' => '1'),
            array('id' => '611','state_id' => '28','name' => 'Prayagraj','status' => '1'),
            array('id' => '612','state_id' => '28','name' => 'Ambedkar Nagar','status' => '1'),
            array('id' => '615','state_id' => '28','name' => 'Auraiya','status' => '1'),
            array('id' => '616','state_id' => '28','name' => 'Azamgarh','status' => '1'),
            array('id' => '618','state_id' => '28','name' => 'Bahraich','status' => '1'),
            array('id' => '619','state_id' => '28','name' => 'Ballia','status' => '1'),
            array('id' => '620','state_id' => '28','name' => 'Balrampur','status' => '1'),
            array('id' => '621','state_id' => '28','name' => 'Banda','status' => '1'),
            array('id' => '622','state_id' => '28','name' => 'Barabanki','status' => '1'),
            array('id' => '623','state_id' => '28','name' => 'Bareilly','status' => '1'),
            array('id' => '624','state_id' => '28','name' => 'Basti','status' => '1'),
            array('id' => '625','state_id' => '28','name' => 'Bijnor','status' => '1'),
            array('id' => '626','state_id' => '28','name' => 'Badaun','status' => '1'),
            array('id' => '627','state_id' => '28','name' => 'Bulandshahr','status' => '1'),
            array('id' => '628','state_id' => '28','name' => 'Chandauli','status' => '1'),
            array('id' => '629','state_id' => '28','name' => 'Chitrakoot','status' => '1'),
            array('id' => '630','state_id' => '28','name' => 'Deoria','status' => '1'),
            array('id' => '631','state_id' => '28','name' => 'Etah','status' => '1'),
            array('id' => '632','state_id' => '28','name' => 'Etawah','status' => '1'),
            array('id' => '633','state_id' => '28','name' => 'Ayodhya','status' => '1'),
            array('id' => '634','state_id' => '28','name' => 'Farrukhabad','status' => '1'),
            array('id' => '635','state_id' => '28','name' => 'Fatehpur','status' => '1'),
            array('id' => '636','state_id' => '28','name' => 'Firozabad','status' => '1'),
            array('id' => '638','state_id' => '28','name' => 'Ghaziabad','status' => '1'),
            array('id' => '639','state_id' => '28','name' => 'Ghazipur','status' => '1'),
            array('id' => '640','state_id' => '28','name' => 'Gonda','status' => '1'),
            array('id' => '641','state_id' => '28','name' => 'Gorakhpur','status' => '1'),
            array('id' => '644','state_id' => '28','name' => 'Hardoi','status' => '1'),
            array('id' => '646','state_id' => '28','name' => 'Jalaun','status' => '1'),
            array('id' => '647','state_id' => '28','name' => 'Jaunpur','status' => '1'),
            array('id' => '648','state_id' => '28','name' => 'Jhansi','status' => '1'),
            array('id' => '649','state_id' => '28','name' => 'Kannauj','status' => '1'),
            array('id' => '651','state_id' => '28','name' => 'Kanpur Nagar','status' => '1'),
            array('id' => '653','state_id' => '28','name' => 'Kaushambi','status' => '1'),
            array('id' => '654','state_id' => '28','name' => 'Kushinagar','status' => '1'),
            array('id' => '655','state_id' => '28','name' => 'Kheri','status' => '1'),
            array('id' => '656','state_id' => '28','name' => 'Lalitpur','status' => '1'),
            array('id' => '657','state_id' => '28','name' => 'Lucknow','status' => '1'),
            array('id' => '658','state_id' => '28','name' => 'Maharajganj','status' => '1'),
            array('id' => '659','state_id' => '28','name' => 'Mahoba','status' => '1'),
            array('id' => '660','state_id' => '28','name' => 'Mainpuri','status' => '1'),
            array('id' => '661','state_id' => '28','name' => 'Mathura','status' => '1'),
            array('id' => '662','state_id' => '28','name' => 'Mau','status' => '1'),
            array('id' => '663','state_id' => '28','name' => 'Meerut','status' => '1'),
            array('id' => '664','state_id' => '28','name' => 'Mirzapur','status' => '1'),
            array('id' => '665','state_id' => '28','name' => 'Moradabad','status' => '1'),
            array('id' => '666','state_id' => '28','name' => 'Muzaffarnagar','status' => '1'),
            array('id' => '667','state_id' => '28','name' => 'Pilibhit','status' => '1'),
            array('id' => '669','state_id' => '28','name' => 'Rae Bareli','status' => '1'),
            array('id' => '670','state_id' => '28','name' => 'Rampur','status' => '1'),
            array('id' => '671','state_id' => '28','name' => 'Saharanpur','status' => '1'),
            array('id' => '673','state_id' => '28','name' => 'Sant Kabir Nagar','status' => '1'),
            array('id' => '674','state_id' => '28','name' => 'Bhadohi','status' => '1'),
            array('id' => '675','state_id' => '28','name' => 'Shahjahanpur','status' => '1'),
            array('id' => '677','state_id' => '28','name' => 'Shrawasti','status' => '1'),
            array('id' => '678','state_id' => '28','name' => 'Siddharthnagar','status' => '1'),
            array('id' => '679','state_id' => '28','name' => 'Sitapur','status' => '1'),
            array('id' => '680','state_id' => '28','name' => 'Sonbhadra','status' => '1'),
            array('id' => '681','state_id' => '28','name' => 'Sultanpur','status' => '1'),
            array('id' => '682','state_id' => '28','name' => 'Unnao','status' => '1'),
            array('id' => '683','state_id' => '28','name' => 'Varanasi','status' => '1'),
            array('id' => '684','state_id' => '27','name' => 'Almora','status' => '1'),
            array('id' => '685','state_id' => '27','name' => 'Bageshwar','status' => '1'),
            array('id' => '686','state_id' => '27','name' => 'Chamoli','status' => '1'),
            array('id' => '687','state_id' => '27','name' => 'Champawat','status' => '1'),
            array('id' => '688','state_id' => '27','name' => 'Dehradun','status' => '1'),
            array('id' => '689','state_id' => '27','name' => 'Haridwar','status' => '1'),
            array('id' => '690','state_id' => '27','name' => 'Nainital','status' => '1'),
            array('id' => '691','state_id' => '27','name' => 'Pauri Garhwal','status' => '1'),
            array('id' => '692','state_id' => '27','name' => 'Pithoragarh','status' => '1'),
            array('id' => '693','state_id' => '27','name' => 'Rudraprayag','status' => '1'),
            array('id' => '694','state_id' => '27','name' => 'Tehri Garhwal','status' => '1'),
            array('id' => '695','state_id' => '27','name' => 'Udham Singh Nagar','status' => '1'),
            array('id' => '696','state_id' => '27','name' => 'Uttarkashi','status' => '1'),
            array('id' => '697','state_id' => '29','name' => 'Alipurduar','status' => '1'),
            array('id' => '698','state_id' => '29','name' => 'Bankura','status' => '1'),
            array('id' => '699','state_id' => '29','name' => 'Paschim Bardhaman','status' => '1'),
            array('id' => '700','state_id' => '29','name' => 'Purba Bardhaman','status' => '1'),
            array('id' => '701','state_id' => '29','name' => 'Birbhum','status' => '1'),
            array('id' => '703','state_id' => '29','name' => 'Dakshin Dinajpur','status' => '1'),
            array('id' => '704','state_id' => '29','name' => 'Darjeeling','status' => '1'),
            array('id' => '705','state_id' => '29','name' => 'Hooghly','status' => '1'),
            array('id' => '706','state_id' => '29','name' => 'Howrah','status' => '1'),
            array('id' => '707','state_id' => '29','name' => 'Jalpaiguri','status' => '1'),
            array('id' => '708','state_id' => '29','name' => 'Jhargram','status' => '1'),
            array('id' => '709','state_id' => '29','name' => 'Kalimpong','status' => '1'),
            array('id' => '710','state_id' => '29','name' => 'Kolkata','status' => '1'),
            array('id' => '712','state_id' => '29','name' => 'Murshidabad','status' => '1'),
            array('id' => '713','state_id' => '29','name' => 'Nadia','status' => '1'),
            array('id' => '714','state_id' => '29','name' => 'North 24 Parganas','status' => '1'),
            array('id' => '715','state_id' => '29','name' => 'Paschim Medinipur','status' => '1'),
            array('id' => '716','state_id' => '29','name' => 'Purbo Medinipur','status' => '1'),
            array('id' => '717','state_id' => '29','name' => 'Purulia','status' => '1'),
            array('id' => '718','state_id' => '29','name' => 'South 24 Parganas','status' => '1'),
            array('id' => '719','state_id' => '29','name' => 'Uttar Dinajpur','status' => '1'),
            array('id' => '722','state_id' => '28','name' => 'Kanpur Dehat','status' => '1'),
            array('id' => '723','state_id' => '28','name' => 'Amethi','status' => '1'),
            array('id' => '726','state_id' => '28','name' => 'Amroha','status' => '1'),
            array('id' => '727','state_id' => '28','name' => 'Baghpat','status' => '1'),
            array('id' => '728','state_id' => '28','name' => 'Gautam Buddha Nagar','status' => '1'),
            array('id' => '729','state_id' => '28','name' => 'Hapur','status' => '1'),
            array('id' => '730','state_id' => '28','name' => 'Sambhal','status' => '1'),
            array('id' => '731','state_id' => '28','name' => 'Shamli','status' => '1'),
            array('id' => '734','state_id' => '28','name' => 'Hathras','status' => '1'),
            array('id' => '735','state_id' => '28','name' => 'Kasganj','status' => '1'),
            array('id' => '739','state_id' => '2','name' => 'Capital Itanagar','status' => '1'),
            array('id' => '740','state_id' => '2','name' => 'Papumpare','status' => '1'),
            array('id' => '741','state_id' => '2','name' => 'Kra Dadi','status' => '1'),
            array('id' => '742','state_id' => '2','name' => 'Kurung Kumey','status' => '1'),
            array('id' => '744','state_id' => '29','name' => 'Coochbehar','status' => '1'),
            array('id' => '748','state_id' => '29','name' => 'Malda','status' => '1'),
            array('id' => '752','state_id' => '20','name' => 'Bolangir','status' => '1'),
            array('id' => '753','state_id' => '20','name' => 'Keonjhar','status' => '1'),
            array('id' => '755','state_id' => '20','name' => 'Khurda','status' => '1'),
            array('id' => '756','state_id' => '20','name' => 'Deogarh','status' => '1'),
            array('id' => '757','state_id' => '20','name' => 'Boudh','status' => '1'),
            array('id' => '759','state_id' => '16','name' => 'Kangpokpi','status' => '1'),
            array('id' => '761','state_id' => '10','name' => 'Badgam','status' => '1'),
            array('id' => '762','state_id' => '38','name' => 'Leh','status' => '1'),
            array('id' => '1178','state_id' => '25','name' => 'Mulugu','status' => '1'),
            array('id' => '1179','state_id' => '25','name' => 'Narayanpet','status' => '1'),
            array('id' => '1181','state_id' => '19','name' => 'Pughoboto','status' => '1'),
            array('id' => '2013','state_id' => '12','name' => 'Gulbarga','status' => '1'),
            array('id' => '2148','state_id' => '32','name' => 'Daman','status' => '1'),
            array('id' => '2149','state_id' => '32','name' => 'Diu','status' => '1'),
            array('id' => '2180','state_id' => '5','name' => 'Gorela Pendra Marwahi','status' => '1'),
            array('id' => '2319','state_id' => '14','name' => 'Niwari','status' => '1'),
            array('id' => '2329','state_id' => '12','name' => 'Vijayanagara','status' => '1'),
            array('id' => '2330','state_id' => '21','name' => 'Malerkotla','status' => '1'),
            array('id' => '2332','state_id' => '24','name' => 'Kallakurichi','status' => '1'),
            array('id' => '2333','state_id' => '24','name' => 'Tenkasi','status' => '1'),
            array('id' => '2334','state_id' => '24','name' => 'Chengalpattu','status' => '1'),
            array('id' => '2335','state_id' => '24','name' => 'Tirupathur','status' => '1'),
            array('id' => '2336','state_id' => '24','name' => 'Ranipet','status' => '1'),
            array('id' => '2337','state_id' => '23','name' => 'Pakyong','status' => '1'),
            array('id' => '2338','state_id' => '23','name' => 'Geyzing','status' => '1'),
            array('id' => '2401','state_id' => '18','name' => 'Saitual','status' => '1'),
            array('id' => '2402','state_id' => '18','name' => 'Khawzawl','status' => '1'),
            array('id' => '2403','state_id' => '18','name' => 'Hnahthial','status' => '1'),
            array('id' => '2404','state_id' => '19','name' => 'Noklak','status' => '1'),
            array('id' => '2405','state_id' => '24','name' => 'Mayiladuthurai','status' => '1'),
            array('id' => '2406','state_id' => '17','name' => 'Eastern West Khasi Hills','status' => '1'),
            array('id' => '2407','state_id' => '1','name' => 'Alluri Seetharama Raju','status' => '1'),
            array('id' => '2408','state_id' => '1','name' => 'Anakapalli','status' => '1'),
            array('id' => '2409','state_id' => '1','name' => 'Annamaiah','status' => '1'),
            array('id' => '2410','state_id' => '1','name' => 'Bapatla','status' => '1'),
            array('id' => '2411','state_id' => '1','name' => 'Eluru','status' => '1'),
            array('id' => '2412','state_id' => '1','name' => 'Kakinada','status' => '1'),
            array('id' => '2413','state_id' => '1','name' => 'Konaseema','status' => '1'),
            array('id' => '2414','state_id' => '1','name' => 'Nandyala','status' => '1'),
            array('id' => '2415','state_id' => '1','name' => 'NTR','status' => '1'),
            array('id' => '2416','state_id' => '1','name' => 'Palnadu','status' => '1'),
            array('id' => '2417','state_id' => '1','name' => 'Parvathipuram Manyam','status' => '1'),
            array('id' => '2418','state_id' => '1','name' => 'Sri Sathya Sai','status' => '1'),
            array('id' => '2419','state_id' => '1','name' => 'Tirupati','status' => '1'),
            array('id' => '2420','state_id' => '38','name' => 'Kargil','status' => '1'),
            array('id' => '2431','state_id' => '19','name' => 'Chumoukedima','status' => '1'),
            array('id' => '2432','state_id' => '19','name' => 'Shamator','status' => '1'),
            array('id' => '2433','state_id' => '19','name' => 'Tseminyu','status' => '1'),
            array('id' => '2434','state_id' => '10','name' => 'Kashmir Displaced','status' => '1'),
            array('id' => '2435','state_id' => '5','name' => 'Khairagarh-Chhuikhadan-Gandai','status' => '1'),
            array('id' => '2436','state_id' => '5','name' => 'Manendragarh-Chirmiri-Bharatpur','status' => '1'),
            array('id' => '2437','state_id' => '5','name' => 'Mohla-Manpur- Ambagarh Chowki','status' => '1'),
            array('id' => '2438','state_id' => '5','name' => 'Sakti','status' => '1'),
            array('id' => '2439','state_id' => '5','name' => 'Sarangarh-Bilaigarh','status' => '1'),
            array('id' => '2448','state_id' => '16','name' => 'Noney','status' => '1'),
            array('id' => '2449','state_id' => '3','name' => 'Bajali','status' => '1'),
            array('id' => '2450','state_id' => '3','name' => 'Biswanath','status' => '1'),
            array('id' => '2451','state_id' => '3','name' => 'Hojai','status' => '1'),
            array('id' => '2452','state_id' => '3','name' => 'Tamulpur','status' => '1'),
            array('id' => '2453','state_id' => '14','name' => 'Mauganj','status' => '1'),
            array('id' => '2454','state_id' => '1','name' => 'Karim Nagar','status' => '1'),
            array('id' => '2455','state_id' => '1','name' => 'Mahabub Nagar','status' => '1'),
            array('id' => '2456','state_id' => '1','name' => 'K.v.rangareddy','status' => '1'),
            array('id' => '2457','state_id' => '1','name' => 'Ananthapur','status' => '1'),
            array('id' => '2458','state_id' => '1','name' => 'Cuddapah','status' => '1'),
            array('id' => '2459','state_id' => '1','name' => 'Nellore','status' => '1'),
            array('id' => '2460','state_id' => '39','name' => 'Pondicherry','status' => '1'),
            array('id' => '2461','state_id' => '3','name' => 'North Cachar Hills','status' => '1'),
            array('id' => '2462','state_id' => '3','name' => 'Marigaon','status' => '1'),
            array('id' => '2463','state_id' => '4','name' => 'East Champaran','status' => '1'),
            array('id' => '2464','state_id' => '4','name' => 'West Champaran','status' => '1'),
            array('id' => '2465','state_id' => '4','name' => 'Aurangabad(bh)','status' => '1'),
            array('id' => '2466','state_id' => '4','name' => 'Kaimur (bhabua)','status' => '1'),
            array('id' => '2467','state_id' => '40','name' => 'Kanker','status' => '1'),
            array('id' => '2468','state_id' => '40','name' => 'Bastar','status' => '1'),
            array('id' => '2469','state_id' => '40','name' => 'Dantewada','status' => '1'),
            array('id' => '2470','state_id' => '40','name' => 'Bijapur(cgh)','status' => '1'),
            array('id' => '2471','state_id' => '40','name' => 'Janjgir-champa','status' => '1'),
            array('id' => '2472','state_id' => '40','name' => 'Bilaspur(cgh)','status' => '1'),
            array('id' => '2473','state_id' => '40','name' => 'Kawardha','status' => '1'),
            array('id' => '2474','state_id' => '40','name' => 'Surguja','status' => '1'),
            array('id' => '2475','state_id' => '40','name' => 'Koriya','status' => '1'),
            array('id' => '2476','state_id' => '40','name' => 'Gariaband','status' => '1'),
            array('id' => '2477','state_id' => '7','name' => 'Gandhi Nagar','status' => '1'),
            array('id' => '2478','state_id' => '7','name' => 'Surendra Nagar','status' => '1'),
            array('id' => '2479','state_id' => '7','name' => 'The Dangs','status' => '1'),
            array('id' => '2480','state_id' => '7','name' => 'Panch Mahals','status' => '1'),
            array('id' => '2481','state_id' => '42','name' => 'Dadra & Nagar Haveli','status' => '1'),
            array('id' => '2482','state_id' => '8','name' => 'Yamuna Nagar','status' => '1'),
            array('id' => '2483','state_id' => '8','name' => 'Hisar','status' => '1'),
            array('id' => '2484','state_id' => '9','name' => 'Hamirpur(hp)','status' => '1'),
            array('id' => '2485','state_id' => '9','name' => 'Bilaspur (hp)','status' => '1'),
            array('id' => '2486','state_id' => '9','name' => 'Lahul & Spiti','status' => '1'),
            array('id' => '2487','state_id' => '9','name' => 'Sirmaur','status' => '1'),
            array('id' => '2488','state_id' => '43','name' => 'Baramulla','status' => '1'),
            array('id' => '2489','state_id' => '43','name' => 'Ananthnag','status' => '1'),
            array('id' => '2490','state_id' => '43','name' => 'Budgam','status' => '1'),
            array('id' => '2491','state_id' => '11','name' => 'Giridh','status' => '1'),
            array('id' => '2492','state_id' => '11','name' => 'Hazaribag','status' => '1'),
            array('id' => '2493','state_id' => '11','name' => 'Palamau','status' => '1'),
            array('id' => '2494','state_id' => '11','name' => 'Sahibganj','status' => '1'),
            array('id' => '2495','state_id' => '11','name' => 'Seraikela-kharsawan','status' => '1'),
            array('id' => '2496','state_id' => '12','name' => 'Bangalore','status' => '1'),
            array('id' => '2497','state_id' => '12','name' => 'Ramanagar','status' => '1'),
            array('id' => '2498','state_id' => '12','name' => 'Bijapur(kar)','status' => '1'),
            array('id' => '2499','state_id' => '12','name' => 'Belgaum','status' => '1'),
            array('id' => '2500','state_id' => '12','name' => 'Chickmagalur','status' => '1'),
            array('id' => '2501','state_id' => '12','name' => 'Chamrajnagar','status' => '1'),
            array('id' => '2502','state_id' => '13','name' => 'Kasargod','status' => '1'),
            array('id' => '2503','state_id' => '14','name' => 'Hoshangabad','status' => '1'),
            array('id' => '2504','state_id' => '14','name' => 'West Nimar','status' => '1'),
            array('id' => '2505','state_id' => '14','name' => 'East Nimar','status' => '1'),
            array('id' => '2506','state_id' => '14','name' => 'Khargone','status' => '1'),
            array('id' => '2507','state_id' => '14','name' => 'Khandwa','status' => '1'),
            array('id' => '2508','state_id' => '15','name' => 'Osmanabad','status' => '1'),
            array('id' => '2509','state_id' => '15','name' => 'Mumbai','status' => '1'),
            array('id' => '2510','state_id' => '15','name' => 'Raigarh(mh)','status' => '1'),
            array('id' => '2511','state_id' => '15','name' => 'Gondia','status' => '1'),
            array('id' => '2512','state_id' => '15','name' => 'Ahmed Nagar','status' => '1'),
            array('id' => '2513','state_id' => '18','name' => 'Mammit','status' => '1'),
            array('id' => '2514','state_id' => '18','name' => 'Saiha','status' => '1'),
            array('id' => '2515','state_id' => '19','name' => 'Zunhebotto','status' => '1'),
            array('id' => '2516','state_id' => '2','name' => 'Papum Pare','status' => '1'),
            array('id' => '2517','state_id' => '17','name' => 'Jaintia Hills','status' => '1'),
            array('id' => '2518','state_id' => '17','name' => 'Ri Bhoi','status' => '1'),
            array('id' => '2519','state_id' => '20','name' => 'Nabarangapur','status' => '1'),
            array('id' => '2520','state_id' => '20','name' => 'Baleswar','status' => '1'),
            array('id' => '2521','state_id' => '20','name' => 'Kendujhar','status' => '1'),
            array('id' => '2522','state_id' => '20','name' => 'Khorda','status' => '1'),
            array('id' => '2523','state_id' => '20','name' => 'Jajapur','status' => '1'),
            array('id' => '2524','state_id' => '20','name' => 'Jagatsinghapur','status' => '1'),
            array('id' => '2525','state_id' => '20','name' => 'Sonapur','status' => '1'),
            array('id' => '2526','state_id' => '20','name' => 'Balangir','status' => '1'),
            array('id' => '2527','state_id' => '20','name' => 'Debagarh','status' => '1'),
            array('id' => '2528','state_id' => '20','name' => 'Sundergarh','status' => '1'),
            array('id' => '2529','state_id' => '21','name' => 'Mohali','status' => '1'),
            array('id' => '2530','state_id' => '21','name' => 'Ropar','status' => '1'),
            array('id' => '2531','state_id' => '21','name' => 'Muktsar','status' => '1'),
            array('id' => '2532','state_id' => '21','name' => 'Nawanshahr','status' => '1'),
            array('id' => '2533','state_id' => '22','name' => 'Jhujhunu','status' => '1'),
            array('id' => '2534','state_id' => '22','name' => 'Jalor','status' => '1'),
            array('id' => '2535','state_id' => '24','name' => 'Kanchipuram','status' => '1'),
            array('id' => '2536','state_id' => '24','name' => 'Tiruvallur','status' => '1'),
            array('id' => '2537','state_id' => '24','name' => 'Villupuram','status' => '1'),
            array('id' => '2538','state_id' => '24','name' => 'Nilgiris','status' => '1'),
            array('id' => '2539','state_id' => '24','name' => 'Kanyakumari','status' => '1'),
            array('id' => '2540','state_id' => '24','name' => 'Tuticorin','status' => '1'),
            array('id' => '2541','state_id' => '24','name' => 'Tiruvarur','status' => '1'),
            array('id' => '2542','state_id' => '28','name' => 'Allahabad','status' => '1'),
            array('id' => '2543','state_id' => '28','name' => 'Sant Ravidas Nagar','status' => '1'),
            array('id' => '2544','state_id' => '28','name' => 'Budaun','status' => '1'),
            array('id' => '2545','state_id' => '28','name' => 'Bagpat','status' => '1'),
            array('id' => '2546','state_id' => '28','name' => 'Jyotiba Phule Nagar','status' => '1'),
            array('id' => '2547','state_id' => '28','name' => 'Faizabad','status' => '1'),
            array('id' => '2548','state_id' => '28','name' => 'Raebareli','status' => '1'),
            array('id' => '2549','state_id' => '29','name' => 'Cooch Behar','status' => '1'),
            array('id' => '2550','state_id' => '29','name' => 'Darjiling','status' => '1'),
            array('id' => '2551','state_id' => '23','name' => 'North Sikkim','status' => '1'),
            array('id' => '2552','state_id' => '23','name' => 'East Sikkim','status' => '1'),
            array('id' => '2553','state_id' => '23','name' => 'West Sikkim','status' => '1'),
            array('id' => '2554','state_id' => '23','name' => 'South Sikkim','status' => '1'),
            array('id' => '2555','state_id' => '29','name' => 'South Dinajpur','status' => '1'),
            array('id' => '2556','state_id' => '29','name' => 'North Dinajpur','status' => '1'),
            array('id' => '2557','state_id' => '29','name' => 'Bardhaman','status' => '1'),
            array('id' => '2558','state_id' => '29','name' => 'East Midnapore','status' => '1'),
            array('id' => '2559','state_id' => '29','name' => 'West Midnapore','status' => '1'),
            array('id' => '2560','state_id' => '29','name' => 'Medinipur','status' => '1'),
            array('id' => '2561','state_id' => '29','name' => 'Puruliya','status' => '1')
        ));

        $batchSize = 500;

        District::truncate();

        $collection->chunk($batchSize)->each(function ($chunk) {
            District::insert($chunk->toArray());
        });

        District::query()->update([
            'created_at' => now(),
            'updated_at' => now()
        ]);
    }
}
