<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Zilla;

class ZillaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $collection = collect(array(
            array('id' => '1','state_id' => '12','name' => 'Mysore City'),
            array('id' => '2','state_id' => '12','name' => 'Mysore Rural'),
            array('id' => '3','state_id' => '12','name' => 'Chamarajanagar'),
            array('id' => '4','state_id' => '12','name' => 'Mandya'),
            array('id' => '5','state_id' => '12','name' => 'Hassan'),
            array('id' => '6','state_id' => '12','name' => 'Kodagu'),
            array('id' => '7','state_id' => '12','name' => 'Dakshina Kannada'),
            array('id' => '8','state_id' => '12','name' => 'Udupi'),
            array('id' => '9','state_id' => '12','name' => 'Chikkamagaluru'),
            array('id' => '10','state_id' => '12','name' => 'Shivamogga'),
            array('id' => '11','state_id' => '12','name' => 'Uttara Kannada'),
            array('id' => '12','state_id' => '12','name' => 'Haveri'),
            array('id' => '13','state_id' => '12','name' => 'Hubblli - Dharwad'),
            array('id' => '14','state_id' => '12','name' => 'Dharwad Rural'),
            array('id' => '15','state_id' => '12','name' => 'Gadag'),
            array('id' => '16','state_id' => '12','name' => 'Belagavi City'),
            array('id' => '17','state_id' => '12','name' => 'Belagavi Rural'),
            array('id' => '18','state_id' => '12','name' => 'Chikkodi'),
            array('id' => '19','state_id' => '12','name' => 'Bagalkot'),
            array('id' => '20','state_id' => '12','name' => 'Vijayapura'),
            array('id' => '21','state_id' => '12','name' => 'Bidar'),
            array('id' => '22','state_id' => '12','name' => 'Kalaburagi City'),
            array('id' => '23','state_id' => '12','name' => 'Kalaburagi Rural'),
            array('id' => '24','state_id' => '12','name' => 'Yadagiri'),
            array('id' => '25','state_id' => '12','name' => 'Raichur'),
            array('id' => '26','state_id' => '12','name' => 'Koppala'),
            array('id' => '27','state_id' => '12','name' => 'Ballari'),
            array('id' => '28','state_id' => '12','name' => 'Davanagere'),
            array('id' => '29','state_id' => '12','name' => 'Chitradurga'),
            array('id' => '30','state_id' => '12','name' => 'Tumakuru'),
            array('id' => '31','state_id' => '12','name' => 'Ramanagar'),
            array('id' => '32','state_id' => '12','name' => 'Bengaluru Rural'),
            array('id' => '33','state_id' => '12','name' => 'Chikkaballapura'),
            array('id' => '34','state_id' => '12','name' => 'Kolara'),
            array('id' => '35','state_id' => '12','name' => 'Bengaluru South'),
            array('id' => '36','state_id' => '12','name' => 'Bengaluru North'),
            array('id' => '37','state_id' => '25','name' => 'Adilabad'),
            array('id' => '38','state_id' => '25','name' => 'Bhadaradri Kothagudem'),
            array('id' => '39','state_id' => '25','name' => 'Hyderabad Central'),
            array('id' => '40','state_id' => '25','name' => 'Jagityal'),
            array('id' => '41','state_id' => '25','name' => 'Jangaon'),
            array('id' => '42','state_id' => '25','name' => 'Jayashankar Bhupalpalle'),
            array('id' => '43','state_id' => '25','name' => 'Jogulamba Gadwal'),
            array('id' => '44','state_id' => '25','name' => 'Kamareddy'),
            array('id' => '45','state_id' => '25','name' => 'Karimnagar'),
            array('id' => '46','state_id' => '25','name' => 'Khammam'),
            array('id' => '47','state_id' => '25','name' => 'Komarambheem Asifabad'),
            array('id' => '48','state_id' => '25','name' => 'Mahabubabad'),
            array('id' => '49','state_id' => '25','name' => 'Mahabubnagar'),
            array('id' => '50','state_id' => '25','name' => 'Mancherial'),
            array('id' => '51','state_id' => '25','name' => 'Medak'),
            array('id' => '52','state_id' => '25','name' => 'Medchal Malkajgiri Urban'),
            array('id' => '53','state_id' => '25','name' => 'Nagarkurnool'),
            array('id' => '54','state_id' => '25','name' => 'Nalgonda'),
            array('id' => '55','state_id' => '25','name' => 'Nirmal'),
            array('id' => '56','state_id' => '25','name' => 'Nizamabad'),
            array('id' => '57','state_id' => '25','name' => 'Peddapalli'),
            array('id' => '58','state_id' => '25','name' => 'Rajanna Sircilla'),
            array('id' => '59','state_id' => '25','name' => 'Rangareddy Urban'),
            array('id' => '60','state_id' => '25','name' => 'Sangareddy'),
            array('id' => '61','state_id' => '25','name' => 'Siddipet'),
            array('id' => '62','state_id' => '25','name' => 'Suryapet'),
            array('id' => '63','state_id' => '25','name' => 'Vikarabad'),
            array('id' => '64','state_id' => '25','name' => 'Wanaparthy'),
            array('id' => '65','state_id' => '25','name' => 'Warangal'),
            array('id' => '66','state_id' => '25','name' => 'Hanmakonda'),
            array('id' => '67','state_id' => '25','name' => 'Yadadri Bhongir'),
            array('id' => '68','state_id' => '9','name' => 'Chamba'),
            array('id' => '69','state_id' => '9','name' => 'Noorpur'),
            array('id' => '70','state_id' => '9','name' => 'Dehra'),
            array('id' => '71','state_id' => '9','name' => 'Palampur'),
            array('id' => '72','state_id' => '9','name' => 'Kangra'),
            array('id' => '73','state_id' => '9','name' => 'Lahol Spiti'),
            array('id' => '74','state_id' => '9','name' => 'Kullu'),
            array('id' => '75','state_id' => '9','name' => 'Sundarnagar'),
            array('id' => '76','state_id' => '9','name' => 'Mandi'),
            array('id' => '77','state_id' => '9','name' => 'Hamirpur'),
            array('id' => '78','state_id' => '9','name' => 'Unna'),
            array('id' => '80','state_id' => '9','name' => 'Solan'),
            array('id' => '81','state_id' => '9','name' => 'Sirmaur'),
            array('id' => '82','state_id' => '9','name' => 'Mahasu'),
            array('id' => '83','state_id' => '9','name' => 'Shimla'),
            array('id' => '84','state_id' => '9','name' => 'Kinaur'),
            array('id' => '255','state_id' => '3','name' => 'Karimaganj'),
            array('id' => '256','state_id' => '3','name' => 'Hailakandi'),
            array('id' => '257','state_id' => '3','name' => 'Cachar'),
            array('id' => '258','state_id' => '3','name' => 'Dima Hasao'),
            array('id' => '259','state_id' => '3','name' => 'East Karbi Anglong'),
            array('id' => '260','state_id' => '3','name' => 'West Karbi Anglong'),
            array('id' => '261','state_id' => '3','name' => 'Bilasipara'),
            array('id' => '262','state_id' => '3','name' => 'Dhubri'),
            array('id' => '263','state_id' => '3','name' => 'South Salmara Mankachar'),
            array('id' => '264','state_id' => '3','name' => 'Goalpara'),
            array('id' => '265','state_id' => '3','name' => 'Kokrajhar'),
            array('id' => '266','state_id' => '3','name' => 'Chirang'),
            array('id' => '267','state_id' => '3','name' => 'Baksa'),
            array('id' => '268','state_id' => '3','name' => 'Bajali'),
            array('id' => '269','state_id' => '3','name' => 'Bongaigaon'),
            array('id' => '270','state_id' => '3','name' => 'Barpeta'),
            array('id' => '271','state_id' => '3','name' => 'Nalbari'),
            array('id' => '272','state_id' => '3','name' => 'South Kamrup'),
            array('id' => '273','state_id' => '3','name' => 'Guwahati City'),
            array('id' => '274','state_id' => '3','name' => 'North Kamrup'),
            array('id' => '275','state_id' => '3','name' => 'Darrang'),
            array('id' => '276','state_id' => '3','name' => 'Udalguri'),
            array('id' => '277','state_id' => '3','name' => 'Sonitpur'),
            array('id' => '278','state_id' => '3','name' => 'Biswanath'),
            array('id' => '279','state_id' => '3','name' => 'Marigaon'),
            array('id' => '280','state_id' => '3','name' => 'Nagaon'),
            array('id' => '281','state_id' => '3','name' => 'Hojai'),
            array('id' => '282','state_id' => '3','name' => 'Kaliabor'),
            array('id' => '283','state_id' => '3','name' => 'Golaghat'),
            array('id' => '284','state_id' => '3','name' => 'Jorhat'),
            array('id' => '285','state_id' => '3','name' => 'Sivsagar'),
            array('id' => '286','state_id' => '3','name' => 'Charaideo'),
            array('id' => '287','state_id' => '3','name' => 'Dibrugarh'),
            array('id' => '288','state_id' => '3','name' => 'Tinsukia'),
            array('id' => '289','state_id' => '3','name' => 'Majuli'),
            array('id' => '290','state_id' => '3','name' => 'Lakhimpur'),
            array('id' => '291','state_id' => '3','name' => 'Dhemaji'),
            array('id' => '293','state_id' => '14','name' => 'Morena'),
            array('id' => '294','state_id' => '14','name' => 'Bhind'),
            array('id' => '295','state_id' => '14','name' => 'Datia'),
            array('id' => '296','state_id' => '14','name' => 'Gwalior Nagar'),
            array('id' => '297','state_id' => '14','name' => 'Gwalior Gramin'),
            array('id' => '298','state_id' => '14','name' => 'Sheopur'),
            array('id' => '299','state_id' => '14','name' => 'Shivpuri'),
            array('id' => '300','state_id' => '14','name' => 'Guna'),
            array('id' => '301','state_id' => '14','name' => 'Sagar'),
            array('id' => '302','state_id' => '14','name' => 'Tikamgarh'),
            array('id' => '303','state_id' => '14','name' => 'Chhatarpur'),
            array('id' => '304','state_id' => '14','name' => 'Damoh'),
            array('id' => '305','state_id' => '14','name' => 'Panna'),
            array('id' => '306','state_id' => '14','name' => 'Satna'),
            array('id' => '307','state_id' => '14','name' => 'Rewa'),
            array('id' => '308','state_id' => '14','name' => 'Sidhi'),
            array('id' => '309','state_id' => '14','name' => 'Singrauli'),
            array('id' => '310','state_id' => '14','name' => 'Shahdol'),
            array('id' => '311','state_id' => '14','name' => 'Umaria'),
            array('id' => '312','state_id' => '14','name' => 'Anuppur'),
            array('id' => '313','state_id' => '14','name' => 'Jabalpur Nagar'),
            array('id' => '314','state_id' => '14','name' => 'Jabalpur Gramin'),
            array('id' => '315','state_id' => '14','name' => 'Katni'),
            array('id' => '316','state_id' => '14','name' => 'Dindori'),
            array('id' => '317','state_id' => '14','name' => 'Mandla'),
            array('id' => '318','state_id' => '14','name' => 'Balaghat'),
            array('id' => '319','state_id' => '14','name' => 'Seoni'),
            array('id' => '320','state_id' => '14','name' => 'Narsinghpur'),
            array('id' => '321','state_id' => '14','name' => 'Chhindwara'),
            array('id' => '322','state_id' => '14','name' => 'Narmadapuram'),
            array('id' => '323','state_id' => '14','name' => 'Harda'),
            array('id' => '324','state_id' => '14','name' => 'Betul'),
            array('id' => '325','state_id' => '14','name' => 'Bhopal Nagar'),
            array('id' => '326','state_id' => '14','name' => 'Bhopal Gramin'),
            array('id' => '327','state_id' => '14','name' => 'Raisen'),
            array('id' => '328','state_id' => '14','name' => 'Vidisha'),
            array('id' => '329','state_id' => '14','name' => 'Sehore'),
            array('id' => '330','state_id' => '14','name' => 'Rajgarh'),
            array('id' => '331','state_id' => '14','name' => 'Indore Nagar'),
            array('id' => '332','state_id' => '14','name' => 'Indore Gramin'),
            array('id' => '333','state_id' => '14','name' => 'Khandwa'),
            array('id' => '334','state_id' => '14','name' => 'Burhanpur'),
            array('id' => '335','state_id' => '14','name' => 'Khargone'),
            array('id' => '336','state_id' => '14','name' => 'Badwani'),
            array('id' => '337','state_id' => '14','name' => 'Alirajpur'),
            array('id' => '338','state_id' => '14','name' => 'Jhabua'),
            array('id' => '339','state_id' => '14','name' => 'Dhar'),
            array('id' => '340','state_id' => '14','name' => 'Ujjain Nagar'),
            array('id' => '341','state_id' => '14','name' => 'Ujjain Gramin'),
            array('id' => '342','state_id' => '14','name' => 'Shajapur'),
            array('id' => '343','state_id' => '14','name' => 'Agar'),
            array('id' => '344','state_id' => '14','name' => 'Dewas'),
            array('id' => '345','state_id' => '14','name' => 'Ratlam'),
            array('id' => '346','state_id' => '14','name' => 'Mandsaur'),
            array('id' => '347','state_id' => '14','name' => 'Neemuch'),
            array('id' => '348','state_id' => '4','name' => 'Bagaha'),
            array('id' => '349','state_id' => '4','name' => 'Bettiah'),
            array('id' => '350','state_id' => '4','name' => 'Motihari'),
            array('id' => '351','state_id' => '4','name' => 'Raxaul'),
            array('id' => '352','state_id' => '4','name' => 'Dhaka'),
            array('id' => '353','state_id' => '4','name' => 'Gopalganj'),
            array('id' => '354','state_id' => '4','name' => 'Siwan'),
            array('id' => '355','state_id' => '4','name' => 'Vaishali (Hajipur)'),
            array('id' => '356','state_id' => '4','name' => 'Chapra (Saran)'),
            array('id' => '357','state_id' => '4','name' => 'Muzaffarpur'),
            array('id' => '358','state_id' => '4','name' => 'Sitamarhi'),
            array('id' => '359','state_id' => '4','name' => 'Sheohar'),
            array('id' => '360','state_id' => '4','name' => 'Madhubani'),
            array('id' => '361','state_id' => '4','name' => 'Jhanjharpur'),
            array('id' => '362','state_id' => '4','name' => 'Darbhanga'),
            array('id' => '363','state_id' => '4','name' => 'Begusarai'),
            array('id' => '364','state_id' => '4','name' => 'Samastipur'),
            array('id' => '365','state_id' => '4','name' => 'Khagaria'),
            array('id' => '366','state_id' => '4','name' => 'Navgachhiya'),
            array('id' => '367','state_id' => '4','name' => 'Supaul'),
            array('id' => '368','state_id' => '4','name' => 'Katihar'),
            array('id' => '369','state_id' => '4','name' => 'Araria'),
            array('id' => '370','state_id' => '4','name' => 'Madhepura'),
            array('id' => '371','state_id' => '4','name' => 'Saharsa'),
            array('id' => '372','state_id' => '4','name' => 'Purnia'),
            array('id' => '373','state_id' => '4','name' => 'Kishanganj'),
            array('id' => '374','state_id' => '4','name' => 'Bhagalpur'),
            array('id' => '375','state_id' => '4','name' => 'Baanka'),
            array('id' => '376','state_id' => '4','name' => 'Jamui'),
            array('id' => '377','state_id' => '4','name' => 'Munger'),
            array('id' => '378','state_id' => '4','name' => 'Lakhisarai'),
            array('id' => '379','state_id' => '4','name' => 'Shekhpura'),
            array('id' => '380','state_id' => '4','name' => 'Nalanda'),
            array('id' => '381','state_id' => '4','name' => 'Nawada'),
            array('id' => '382','state_id' => '4','name' => 'Gaya'),
            array('id' => '383','state_id' => '4','name' => 'Jehanabad'),
            array('id' => '384','state_id' => '4','name' => 'Arwal'),
            array('id' => '385','state_id' => '4','name' => 'Aurangabad'),
            array('id' => '386','state_id' => '4','name' => 'Rohtas'),
            array('id' => '387','state_id' => '4','name' => 'Kaimur'),
            array('id' => '388','state_id' => '4','name' => 'Buxar'),
            array('id' => '389','state_id' => '4','name' => 'Bhojpur'),
            array('id' => '390','state_id' => '4','name' => 'Barh'),
            array('id' => '391','state_id' => '4','name' => 'Patna Gramin'),
            array('id' => '392','state_id' => '4','name' => 'Patna Mahanagar'),
            array('id' => '393','state_id' => '7','name' => 'Bhavnagar Dist.'),
            array('id' => '394','state_id' => '7','name' => 'Junagadh Dist.'),
            array('id' => '395','state_id' => '7','name' => 'Kutch'),
            array('id' => '396','state_id' => '7','name' => 'Mehsana'),
            array('id' => '397','state_id' => '7','name' => 'Morbi'),
            array('id' => '398','state_id' => '7','name' => 'Kheda'),
            array('id' => '399','state_id' => '7','name' => 'Narmada'),
            array('id' => '400','state_id' => '7','name' => 'Navsari'),
            array('id' => '401','state_id' => '7','name' => 'Banaskantha'),
            array('id' => '402','state_id' => '7','name' => 'Valsad'),
            array('id' => '403','state_id' => '7','name' => 'Porbandar'),
            array('id' => '404','state_id' => '7','name' => 'Chhota Udaipur'),
            array('id' => '405','state_id' => '7','name' => 'Patan'),
            array('id' => '406','state_id' => '7','name' => 'Tapi'),
            array('id' => '407','state_id' => '7','name' => 'Gir Somnath'),
            array('id' => '408','state_id' => '7','name' => 'Vadodara Dist.'),
            array('id' => '409','state_id' => '7','name' => 'Dahod'),
            array('id' => '410','state_id' => '7','name' => 'Anand'),
            array('id' => '411','state_id' => '7','name' => 'Bharuch'),
            array('id' => '412','state_id' => '7','name' => 'Ahmedabad Dist.'),
            array('id' => '413','state_id' => '7','name' => 'Dev. Dwarka'),
            array('id' => '414','state_id' => '7','name' => 'Bhavnagar City'),
            array('id' => '415','state_id' => '7','name' => 'Surat Dist.'),
            array('id' => '416','state_id' => '7','name' => 'Botad'),
            array('id' => '417','state_id' => '7','name' => 'Panchmahal'),
            array('id' => '418','state_id' => '7','name' => 'Jamnagar Dist.'),
            array('id' => '419','state_id' => '7','name' => 'Gandhinagar Dist.'),
            array('id' => '420','state_id' => '7','name' => 'Amreli'),
            array('id' => '421','state_id' => '7','name' => 'Surendranagar'),
            array('id' => '422','state_id' => '7','name' => 'Dang'),
            array('id' => '423','state_id' => '7','name' => 'Surat City'),
            array('id' => '424','state_id' => '7','name' => 'Karnavati'),
            array('id' => '425','state_id' => '7','name' => 'Gandhinagar City'),
            array('id' => '426','state_id' => '7','name' => 'Sabarkantha'),
            array('id' => '427','state_id' => '7','name' => 'Aravali'),
            array('id' => '428','state_id' => '7','name' => 'Mahisagar'),
            array('id' => '429','state_id' => '7','name' => 'Jamnagar City'),
            array('id' => '430','state_id' => '7','name' => 'Rajkot City'),
            array('id' => '431','state_id' => '7','name' => 'Rajkot Dist.'),
            array('id' => '432','state_id' => '7','name' => 'Junagadh City'),
            array('id' => '433','state_id' => '7','name' => 'Vadodara City'),
            array('id' => '434','state_id' => '21','name' => 'Pathankot'),
            array('id' => '435','state_id' => '21','name' => 'Gurdaspur'),
            array('id' => '436','state_id' => '21','name' => 'Batala'),
            array('id' => '437','state_id' => '21','name' => 'Amritsar Rural'),
            array('id' => '438','state_id' => '21','name' => 'Amritsar Urban'),
            array('id' => '439','state_id' => '21','name' => 'Kapurthala'),
            array('id' => '440','state_id' => '21','name' => 'Hoshiarpur Rural (Mukerian)'),
            array('id' => '441','state_id' => '21','name' => 'Hoshiarpur Urban'),
            array('id' => '482','state_id' => '1','name' => 'Anantapur'),
            array('id' => '483','state_id' => '1','name' => 'Chittoor'),
            array('id' => '484','state_id' => '1','name' => 'Kakinada'),
            array('id' => '485','state_id' => '1','name' => 'Rajahmundry'),
            array('id' => '486','state_id' => '1','name' => 'Guntur'),
            array('id' => '488','state_id' => '1','name' => 'Kadapa'),
            array('id' => '489','state_id' => '1','name' => 'Machilipatnam'),
            array('id' => '490','state_id' => '1','name' => 'Vijayawada'),
            array('id' => '491','state_id' => '1','name' => 'Kurnool'),
            array('id' => '492','state_id' => '1','name' => 'Nellore'),
            array('id' => '493','state_id' => '1','name' => 'Ongole'),
            array('id' => '494','state_id' => '1','name' => 'Srikakulam'),
            array('id' => '495','state_id' => '1','name' => 'Anakapalli'),
            array('id' => '496','state_id' => '1','name' => 'Visakhapatnam'),
            array('id' => '497','state_id' => '1','name' => 'Vizianagaram'),
            array('id' => '498','state_id' => '1','name' => 'Narsapuram'),
            array('id' => '499','state_id' => '15','name' => 'Nandurbar'),
            array('id' => '500','state_id' => '15','name' => 'Dhule Rural'),
            array('id' => '501','state_id' => '15','name' => 'Dhule City'),
            array('id' => '502','state_id' => '15','name' => 'Jalgaon Paschim'),
            array('id' => '503','state_id' => '15','name' => 'Jalgaon City'),
            array('id' => '504','state_id' => '15','name' => 'Buldhana'),
            array('id' => '505','state_id' => '15','name' => 'Akola Rural'),
            array('id' => '506','state_id' => '15','name' => 'Akola City'),
            array('id' => '507','state_id' => '15','name' => 'Washim'),
            array('id' => '508','state_id' => '15','name' => 'Amravati Rural'),
            array('id' => '509','state_id' => '15','name' => 'Amravati City'),
            array('id' => '510','state_id' => '15','name' => 'Wardha'),
            array('id' => '511','state_id' => '15','name' => 'Nagpur Rural'),
            array('id' => '512','state_id' => '15','name' => 'Nagpur City'),
            array('id' => '513','state_id' => '15','name' => 'Bhandara'),
            array('id' => '514','state_id' => '15','name' => 'Gondia'),
            array('id' => '515','state_id' => '15','name' => 'Gadchiroli'),
            array('id' => '516','state_id' => '15','name' => 'Chandrapur Rural'),
            array('id' => '517','state_id' => '15','name' => 'Chandrapur City'),
            array('id' => '518','state_id' => '15','name' => 'Yavatmal'),
            array('id' => '519','state_id' => '15','name' => 'Nanded Dakshin'),
            array('id' => '520','state_id' => '15','name' => 'Nanded City'),
            array('id' => '521','state_id' => '15','name' => 'Hingoli'),
            array('id' => '522','state_id' => '15','name' => 'Parbhani Rural'),
            array('id' => '523','state_id' => '15','name' => 'Parbhani City'),
            array('id' => '524','state_id' => '15','name' => 'Jalna'),
            array('id' => '525','state_id' => '15','name' => 'Sambhaji Nagar Dakshin'),
            array('id' => '526','state_id' => '15','name' => 'Sambhaji Nagar City'),
            array('id' => '527','state_id' => '15','name' => 'Nashik Uttar'),
            array('id' => '528','state_id' => '15','name' => 'Malegaon'),
            array('id' => '529','state_id' => '15','name' => 'Nashik City'),
            array('id' => '530','state_id' => '15','name' => 'Palghar'),
            array('id' => '531','state_id' => '15','name' => 'Vasai Virar'),
            array('id' => '532','state_id' => '15','name' => 'Thane Rural'),
            array('id' => '533','state_id' => '15','name' => 'Bhiwandi'),
            array('id' => '534','state_id' => '15','name' => 'Kalyan'),
            array('id' => '535','state_id' => '15','name' => 'Ulhasnagar'),
            array('id' => '536','state_id' => '15','name' => 'Mira Bhayander'),
            array('id' => '537','state_id' => '15','name' => 'Thane City'),
            array('id' => '538','state_id' => '15','name' => 'Navi Mumbai'),
            array('id' => '545','state_id' => '15','name' => 'Raigad South'),
            array('id' => '546','state_id' => '15','name' => 'Pune (Uttar Maval)'),
            array('id' => '547','state_id' => '15','name' => 'Pimpri Chinchwad'),
            array('id' => '548','state_id' => '15','name' => 'Pune City'),
            array('id' => '549','state_id' => '15','name' => 'Nagar South'),
            array('id' => '550','state_id' => '15','name' => 'Nagar Mahanagar'),
            array('id' => '551','state_id' => '15','name' => 'Beed'),
            array('id' => '552','state_id' => '15','name' => 'Latur Rural'),
            array('id' => '553','state_id' => '15','name' => 'Latur City'),
            array('id' => '554','state_id' => '15','name' => 'Dharashiv'),
            array('id' => '555','state_id' => '15','name' => 'Solapur Purv'),
            array('id' => '556','state_id' => '15','name' => 'Solapur City'),
            array('id' => '557','state_id' => '15','name' => 'Satara'),
            array('id' => '558','state_id' => '15','name' => 'Ratnagiri South'),
            array('id' => '559','state_id' => '15','name' => 'Sindhudurg'),
            array('id' => '560','state_id' => '15','name' => 'Kolhapur Paschim'),
            array('id' => '561','state_id' => '15','name' => 'Kolhapur City'),
            array('id' => '562','state_id' => '15','name' => 'Sangli City'),
            array('id' => '563','state_id' => '15','name' => 'Sangli Rural'),
            array('id' => '565','state_id' => '8','name' => 'Yamunanagar'),
            array('id' => '566','state_id' => '8','name' => 'Jind'),
            array('id' => '569','state_id' => '8','name' => 'Panchkula'),
            array('id' => '570','state_id' => '8','name' => 'Ambala'),
            array('id' => '571','state_id' => '8','name' => 'Kurukshetra'),
            array('id' => '572','state_id' => '8','name' => 'Kaithal'),
            array('id' => '573','state_id' => '8','name' => 'Karnal'),
            array('id' => '574','state_id' => '8','name' => 'Panipat'),
            array('id' => '575','state_id' => '8','name' => 'Sonipat'),
            array('id' => '576','state_id' => '8','name' => 'Fatehabad'),
            array('id' => '577','state_id' => '8','name' => 'Sirsa'),
            array('id' => '578','state_id' => '8','name' => 'Hisar'),
            array('id' => '579','state_id' => '8','name' => 'Charkhi Dadri'),
            array('id' => '580','state_id' => '8','name' => 'Bhiwani'),
            array('id' => '581','state_id' => '8','name' => 'Rohtak'),
            array('id' => '582','state_id' => '8','name' => 'Jhajjar'),
            array('id' => '583','state_id' => '8','name' => 'Mahendragarh'),
            array('id' => '584','state_id' => '8','name' => 'Rewari'),
            array('id' => '585','state_id' => '8','name' => 'Gurugram'),
            array('id' => '586','state_id' => '8','name' => 'Nuh'),
            array('id' => '587','state_id' => '8','name' => 'Palwal'),
            array('id' => '588','state_id' => '8','name' => 'Faridabad'),
            array('id' => '601','state_id' => '30','name' => 'Keshav Puram'),
            array('id' => '602','state_id' => '30','name' => 'Chandni Chowk'),
            array('id' => '603','state_id' => '30','name' => 'North East'),
            array('id' => '604','state_id' => '30','name' => 'Naveen Shahdara'),
            array('id' => '605','state_id' => '30','name' => 'Mayur Vihar'),
            array('id' => '606','state_id' => '30','name' => 'Shahdara'),
            array('id' => '607','state_id' => '30','name' => 'Karol Bagh'),
            array('id' => '608','state_id' => '30','name' => 'New Delhi'),
            array('id' => '609','state_id' => '30','name' => 'North West'),
            array('id' => '610','state_id' => '30','name' => 'Outer Delhi'),
            array('id' => '611','state_id' => '30','name' => 'West Delhi'),
            array('id' => '612','state_id' => '30','name' => 'Najafgarh'),
            array('id' => '613','state_id' => '30','name' => 'Mehrauli'),
            array('id' => '614','state_id' => '30','name' => 'South Delhi'),
            array('id' => '615','state_id' => '11','name' => 'Sahebganj'),
            array('id' => '616','state_id' => '11','name' => 'Godda'),
            array('id' => '617','state_id' => '11','name' => 'Dumka'),
            array('id' => '618','state_id' => '11','name' => 'Pakur'),
            array('id' => '619','state_id' => '11','name' => 'Jamtara'),
            array('id' => '620','state_id' => '11','name' => 'Deoghar'),
            array('id' => '621','state_id' => '11','name' => 'Koderma'),
            array('id' => '622','state_id' => '11','name' => 'Palamu'),
            array('id' => '623','state_id' => '11','name' => 'Giridih'),
            array('id' => '624','state_id' => '11','name' => 'Hazaribagh'),
            array('id' => '625','state_id' => '11','name' => 'Ramgarh'),
            array('id' => '626','state_id' => '11','name' => 'Chatra'),
            array('id' => '627','state_id' => '11','name' => 'Ranchi City'),
            array('id' => '628','state_id' => '11','name' => 'Bokaro'),
            array('id' => '629','state_id' => '11','name' => 'Dhanbad Mahanagar'),
            array('id' => '630','state_id' => '11','name' => 'East Singhbhum'),
            array('id' => '631','state_id' => '11','name' => 'Jamshedpur Maha.'),
            array('id' => '632','state_id' => '11','name' => 'Saraikela-Kharsawan'),
            array('id' => '633','state_id' => '11','name' => 'West Singhbhum'),
            array('id' => '634','state_id' => '11','name' => 'Gumla'),
            array('id' => '635','state_id' => '11','name' => 'Ranchi Rural'),
            array('id' => '636','state_id' => '11','name' => 'Simdega'),
            array('id' => '637','state_id' => '11','name' => 'Khunti'),
            array('id' => '638','state_id' => '11','name' => 'Lohardaga'),
            array('id' => '639','state_id' => '11','name' => 'Latehar'),
            array('id' => '640','state_id' => '11','name' => 'GARHWA'),
            array('id' => '641','state_id' => '26','name' => 'Sadar (Rural)'),
            array('id' => '642','state_id' => '26','name' => 'Sadar (Urban)'),
            array('id' => '643','state_id' => '26','name' => 'Sipahijala (North)'),
            array('id' => '644','state_id' => '26','name' => 'Sipahijala (South)'),
            array('id' => '645','state_id' => '26','name' => 'Khowai'),
            array('id' => '646','state_id' => '26','name' => 'Gomati'),
            array('id' => '647','state_id' => '26','name' => 'South District'),
            array('id' => '648','state_id' => '26','name' => 'Dhalai'),
            array('id' => '649','state_id' => '26','name' => 'Unokuti'),
            array('id' => '650','state_id' => '26','name' => 'North District'),
            array('id' => '685','state_id' => '31','name' => 'Villianur'),
            array('id' => '686','state_id' => '31','name' => 'Oulgrate'),
            array('id' => '687','state_id' => '31','name' => 'Nagar'),
            array('id' => '688','state_id' => '31','name' => 'Ariyankuppam'),
            array('id' => '689','state_id' => '31','name' => 'Karaikal'),
            array('id' => '729','state_id' => '24','name' => 'Thiruvallur East'),
            array('id' => '730','state_id' => '24','name' => 'Thiruvallur West'),
            array('id' => '732','state_id' => '24','name' => 'South Chennai'),
            array('id' => '734','state_id' => '24','name' => 'Central Chennai East'),
            array('id' => '738','state_id' => '24','name' => 'Krishnagiri West'),
            array('id' => '739','state_id' => '24','name' => 'Dharmapuri'),
            array('id' => '740','state_id' => '24','name' => 'Salem West'),
            array('id' => '742','state_id' => '24','name' => 'Villupuram North'),
            array('id' => '744','state_id' => '24','name' => 'Salem East'),
            array('id' => '745','state_id' => '24','name' => 'Salem Nagar'),
            array('id' => '746','state_id' => '24','name' => 'Namakkal West'),
            array('id' => '747','state_id' => '24','name' => 'Erode South'),
            array('id' => '748','state_id' => '24','name' => 'Tiruppur South'),
            array('id' => '749','state_id' => '24','name' => 'Erode North'),
            array('id' => '750','state_id' => '24','name' => 'Tiruppur North'),
            array('id' => '751','state_id' => '24','name' => 'Nilgiris'),
            array('id' => '752','state_id' => '24','name' => 'Coimbatore North'),
            array('id' => '753','state_id' => '24','name' => 'Coimbatore Nagar'),
            array('id' => '754','state_id' => '24','name' => 'Coimbatore South'),
            array('id' => '756','state_id' => '24','name' => 'Karur'),
            array('id' => '757','state_id' => '24','name' => 'Trichy Rural'),
            array('id' => '758','state_id' => '24','name' => 'Pudukkottai East'),
            array('id' => '759','state_id' => '24','name' => 'Trichy Nagar'),
            array('id' => '760','state_id' => '24','name' => 'Perambalur'),
            array('id' => '762','state_id' => '24','name' => 'Ariyalur'),
            array('id' => '763','state_id' => '24','name' => 'Mayiladuthurai'),
            array('id' => '764','state_id' => '24','name' => 'Thanjavur North'),
            array('id' => '765','state_id' => '24','name' => 'Nagapattinam'),
            array('id' => '766','state_id' => '24','name' => 'Thiruvarur'),
            array('id' => '767','state_id' => '24','name' => 'Thanjavur South'),
            array('id' => '768','state_id' => '24','name' => 'Sivagangai'),
            array('id' => '769','state_id' => '24','name' => 'Madurai West'),
            array('id' => '770','state_id' => '24','name' => 'Madurai Nagar'),
            array('id' => '771','state_id' => '24','name' => 'Theni'),
            array('id' => '773','state_id' => '24','name' => 'Ramanathapuram'),
            array('id' => '779','state_id' => '34','name' => 'Dr. Bhimrao'),
            array('id' => '780','state_id' => '34','name' => 'Bharat Ratan Atal Nagar'),
            array('id' => '781','state_id' => '34','name' => 'Dr. Shyama Prasad Mukherjee Nagar'),
            array('id' => '782','state_id' => '34','name' => 'Pt. Deen Dayal Upadhyay Nagar'),
            array('id' => '783','state_id' => '34','name' => 'Rani Lakshmi Bai'),
            array('id' => '784','state_id' => '18','name' => 'Mamit'),
            array('id' => '785','state_id' => '18','name' => 'Kolasib'),
            array('id' => '787','state_id' => '18','name' => 'Aizawl'),
            array('id' => '788','state_id' => '18','name' => 'Champhai'),
            array('id' => '789','state_id' => '18','name' => 'Serchhip'),
            array('id' => '790','state_id' => '18','name' => 'Lunglei'),
            array('id' => '791','state_id' => '18','name' => 'Chakma Autonomus'),
            array('id' => '792','state_id' => '18','name' => 'Lawngtlai'),
            array('id' => '793','state_id' => '18','name' => 'Saiha'),
            array('id' => '794','state_id' => '21','name' => 'Barnala'),
            array('id' => '795','state_id' => '21','name' => 'Bathinda Rural'),
            array('id' => '796','state_id' => '21','name' => 'Bathinda Urban'),
            array('id' => '797','state_id' => '21','name' => 'Faridkot'),
            array('id' => '798','state_id' => '21','name' => 'Firozpur'),
            array('id' => '799','state_id' => '21','name' => 'Jagraon'),
            array('id' => '800','state_id' => '21','name' => 'Fatehgarh Sahib'),
            array('id' => '801','state_id' => '21','name' => 'Fazilka'),
            array('id' => '802','state_id' => '21','name' => 'Khanna'),
            array('id' => '803','state_id' => '21','name' => 'Jalandhar Rural (North)'),
            array('id' => '804','state_id' => '21','name' => 'Jalandhar Urban'),
            array('id' => '805','state_id' => '21','name' => 'Ludhiana Urban'),
            array('id' => '806','state_id' => '21','name' => 'Mohali'),
            array('id' => '807','state_id' => '21','name' => 'Mansa'),
            array('id' => '808','state_id' => '21','name' => 'Moga'),
            array('id' => '809','state_id' => '21','name' => 'Patiala Urban'),
            array('id' => '810','state_id' => '21','name' => 'Patiala Rural (South)'),
            array('id' => '811','state_id' => '21','name' => 'Sangrur 1'),
            array('id' => '812','state_id' => '21','name' => 'Sangrur 2'),
            array('id' => '813','state_id' => '21','name' => 'Nawanshahr'),
            array('id' => '814','state_id' => '21','name' => 'Patiala Rural (North)'),
            array('id' => '815','state_id' => '21','name' => 'Ropar'),
            array('id' => '816','state_id' => '21','name' => 'Tarn Taran'),
            array('id' => '817','state_id' => '21','name' => 'Mukatsar'),
            array('id' => '818','state_id' => '21','name' => 'Jalandhar Rural (South)'),
            array('id' => '821','state_id' => '16','name' => 'Imphal East'),
            array('id' => '822','state_id' => '16','name' => 'Imphal Central'),
            array('id' => '824','state_id' => '14','name' => 'Ashok Nagar'),
            array('id' => '838','state_id' => '2','name' => 'Tawang'),
            array('id' => '839','state_id' => '2','name' => 'West Kameng'),
            array('id' => '840','state_id' => '2','name' => 'East Kameng'),
            array('id' => '841','state_id' => '2','name' => 'Itanagar Capital'),
            array('id' => '842','state_id' => '2','name' => 'Papumpare'),
            array('id' => '843','state_id' => '2','name' => 'Lower Subansiri'),
            array('id' => '844','state_id' => '2','name' => 'Kra Dadi'),
            array('id' => '845','state_id' => '2','name' => 'Kurungkumey'),
            array('id' => '846','state_id' => '2','name' => 'Upper Subansiri'),
            array('id' => '847','state_id' => '2','name' => 'Kamle'),
            array('id' => '848','state_id' => '2','name' => 'West Siang'),
            array('id' => '849','state_id' => '2','name' => 'Lower Siang'),
            array('id' => '850','state_id' => '2','name' => 'Upper Siang'),
            array('id' => '851','state_id' => '2','name' => 'Siang'),
            array('id' => '852','state_id' => '2','name' => 'East Siang'),
            array('id' => '853','state_id' => '2','name' => 'Dibang Valley'),
            array('id' => '854','state_id' => '2','name' => 'Lower Dibang Valley'),
            array('id' => '855','state_id' => '2','name' => 'Anjaw'),
            array('id' => '856','state_id' => '2','name' => 'Lohit'),
            array('id' => '857','state_id' => '2','name' => 'Namsai'),
            array('id' => '858','state_id' => '2','name' => 'Changlang'),
            array('id' => '859','state_id' => '2','name' => 'Tirap'),
            array('id' => '860','state_id' => '2','name' => 'Longding'),
            array('id' => '861','state_id' => '24','name' => 'Cuddalore West'),
            array('id' => '862','state_id' => '24','name' => 'Cuddalore East'),
            array('id' => '863','state_id' => '24','name' => 'Thiruvannamalai South'),
            array('id' => '864','state_id' => '24','name' => 'Thiruvannamalai North'),
            array('id' => '867','state_id' => '20','name' => 'Kalahandi'),
            array('id' => '868','state_id' => '20','name' => 'Jajpur'),
            array('id' => '869','state_id' => '20','name' => 'Gajapati'),
            array('id' => '870','state_id' => '20','name' => 'Bargarh'),
            array('id' => '871','state_id' => '20','name' => 'Balangir'),
            array('id' => '872','state_id' => '20','name' => 'Angul'),
            array('id' => '873','state_id' => '20','name' => 'Sambalpur'),
            array('id' => '874','state_id' => '20','name' => 'Bhadrak'),
            array('id' => '875','state_id' => '20','name' => 'Rayagada'),
            array('id' => '876','state_id' => '20','name' => 'Jagatsinghpur'),
            array('id' => '877','state_id' => '20','name' => 'Puri'),
            array('id' => '878','state_id' => '20','name' => 'Koraput'),
            array('id' => '879','state_id' => '20','name' => 'Keonjhar'),
            array('id' => '880','state_id' => '20','name' => 'Nabrangpur'),
            array('id' => '881','state_id' => '20','name' => 'Ghumusar (Ganjam)'),
            array('id' => '882','state_id' => '20','name' => 'Balasore'),
            array('id' => '883','state_id' => '20','name' => 'Kendrapada'),
            array('id' => '884','state_id' => '20','name' => 'Ganjam'),
            array('id' => '885','state_id' => '20','name' => 'Dhenkanal'),
            array('id' => '886','state_id' => '20','name' => 'Cuttack Sadar'),
            array('id' => '887','state_id' => '20','name' => 'Rairangpur (Mayurbhanj)'),
            array('id' => '888','state_id' => '20','name' => 'Malkangiri'),
            array('id' => '889','state_id' => '20','name' => 'Khordha'),
            array('id' => '890','state_id' => '20','name' => 'Baripada(Mayurbhanj)'),
            array('id' => '891','state_id' => '20','name' => 'Sundargarh'),
            array('id' => '892','state_id' => '20','name' => 'Nayagarh'),
            array('id' => '893','state_id' => '20','name' => 'Cuttack City'),
            array('id' => '894','state_id' => '20','name' => 'Kandhamal'),
            array('id' => '895','state_id' => '20','name' => 'Bhubaneswar'),
            array('id' => '896','state_id' => '20','name' => 'Jharsuguda'),
            array('id' => '897','state_id' => '20','name' => 'Panposh (Sundargarh)'),
            array('id' => '898','state_id' => '20','name' => 'Bonai ( Sundargarh)'),
            array('id' => '899','state_id' => '20','name' => 'Nuapada'),
            array('id' => '900','state_id' => '20','name' => 'Deogarh'),
            array('id' => '901','state_id' => '20','name' => 'Boudh'),
            array('id' => '902','state_id' => '20','name' => 'Subarnapur'),
            array('id' => '903','state_id' => '16','name' => 'Imphal West'),
            array('id' => '904','state_id' => '16','name' => 'Bishnupur'),
            array('id' => '905','state_id' => '16','name' => 'Thoubal'),
            array('id' => '906','state_id' => '16','name' => 'Kakching'),
            array('id' => '907','state_id' => '16','name' => 'Chandel'),
            array('id' => '908','state_id' => '16','name' => 'Ukhrul'),
            array('id' => '909','state_id' => '16','name' => 'Sadar Hills'),
            array('id' => '910','state_id' => '16','name' => 'Senapati'),
            array('id' => '911','state_id' => '16','name' => 'Tamenglong'),
            array('id' => '912','state_id' => '16','name' => 'Churachandpur'),
            array('id' => '915','state_id' => '10','name' => 'Kupwara'),
            array('id' => '916','state_id' => '10','name' => 'Baramulla'),
            array('id' => '917','state_id' => '10','name' => 'Bandipora'),
            array('id' => '918','state_id' => '10','name' => 'Ganderbal'),
            array('id' => '919','state_id' => '10','name' => 'Srinagar'),
            array('id' => '920','state_id' => '10','name' => 'Budgam'),
            array('id' => '921','state_id' => '10','name' => 'Pulwama'),
            array('id' => '922','state_id' => '10','name' => 'Shopian'),
            array('id' => '923','state_id' => '10','name' => 'Kulgam'),
            array('id' => '924','state_id' => '10','name' => 'Anantnag'),
            array('id' => '925','state_id' => '38','name' => 'Leh'),
            array('id' => '926','state_id' => '38','name' => 'Kargil'),
            array('id' => '927','state_id' => '10','name' => 'Kishtwar'),
            array('id' => '928','state_id' => '10','name' => 'Doda'),
            array('id' => '929','state_id' => '10','name' => 'Ramban'),
            array('id' => '930','state_id' => '10','name' => 'Reasi'),
            array('id' => '931','state_id' => '10','name' => 'Udhampur'),
            array('id' => '932','state_id' => '10','name' => 'Basohli'),
            array('id' => '933','state_id' => '10','name' => 'Kathua'),
            array('id' => '934','state_id' => '10','name' => 'Samba'),
            array('id' => '935','state_id' => '10','name' => 'Jammu North'),
            array('id' => '936','state_id' => '10','name' => 'Jammu'),
            array('id' => '937','state_id' => '10','name' => 'Jammu South'),
            array('id' => '938','state_id' => '10','name' => 'Jammu Border'),
            array('id' => '939','state_id' => '10','name' => 'Akhnoor'),
            array('id' => '940','state_id' => '10','name' => 'Nowshera'),
            array('id' => '941','state_id' => '10','name' => 'Rajouri'),
            array('id' => '942','state_id' => '10','name' => 'Poonch'),
            array('id' => '943','state_id' => '10','name' => 'Kashmir Displaced'),
            array('id' => '979','state_id' => '6','name' => 'North Goa'),
            array('id' => '980','state_id' => '6','name' => 'South Goa'),
            array('id' => '1000','state_id' => '33','name' => 'Port Blair City'),
            array('id' => '1001','state_id' => '33','name' => 'Nicobar'),
            array('id' => '1002','state_id' => '33','name' => 'South Andaman'),
            array('id' => '1003','state_id' => '33','name' => 'Rangat'),
            array('id' => '1004','state_id' => '33','name' => 'Diglipur'),
            array('id' => '1006','state_id' => '23','name' => 'Soreng'),
            array('id' => '1007','state_id' => '23','name' => 'Namchi'),
            array('id' => '1008','state_id' => '23','name' => 'Gangtok'),
            array('id' => '1009','state_id' => '23','name' => 'Mangan'),
            array('id' => '1011','state_id' => '19','name' => 'Aboi'),
            array('id' => '1012','state_id' => '19','name' => 'Dimapur'),
            array('id' => '1013','state_id' => '19','name' => 'Kiphire'),
            array('id' => '1014','state_id' => '19','name' => 'Kohima'),
            array('id' => '1015','state_id' => '19','name' => 'Longleng'),
            array('id' => '1016','state_id' => '19','name' => 'Mankulumba'),
            array('id' => '1017','state_id' => '19','name' => 'Mokokchung'),
            array('id' => '1018','state_id' => '19','name' => 'Mon'),
            array('id' => '1019','state_id' => '19','name' => 'Noklak'),
            array('id' => '1020','state_id' => '19','name' => 'Peren'),
            array('id' => '1021','state_id' => '19','name' => 'Phek'),
            array('id' => '1022','state_id' => '19','name' => 'Tuensang'),
            array('id' => '1023','state_id' => '19','name' => 'Wokha'),
            array('id' => '1024','state_id' => '19','name' => 'Zunheboto'),
            array('id' => '1025','state_id' => '32','name' => 'Silvassa Gramin'),
            array('id' => '1026','state_id' => '32','name' => 'Khanvel'),
            array('id' => '1086','state_id' => '17','name' => 'West Jaintia Hils'),
            array('id' => '1087','state_id' => '17','name' => 'East Jaintia Hills'),
            array('id' => '1088','state_id' => '17','name' => 'Ri-Bhoi District'),
            array('id' => '1089','state_id' => '17','name' => 'East Khasi Hills'),
            array('id' => '1090','state_id' => '17','name' => 'Shillong City'),
            array('id' => '1091','state_id' => '17','name' => 'West Khasi Hills'),
            array('id' => '1092','state_id' => '17','name' => 'South West Khasi Hills'),
            array('id' => '1093','state_id' => '17','name' => 'North Garo Hills'),
            array('id' => '1094','state_id' => '17','name' => 'East Garo Hills'),
            array('id' => '1095','state_id' => '17','name' => 'West Garo Hills'),
            array('id' => '1096','state_id' => '17','name' => 'Tura City'),
            array('id' => '1097','state_id' => '17','name' => 'South West Garo Hills'),
            array('id' => '1098','state_id' => '17','name' => 'South Garo Hills'),
            array('id' => '1099','state_id' => '3','name' => 'Dhakuakhana'),
            array('id' => '1104','state_id' => '36','name' => 'Agathy'),
            array('id' => '1105','state_id' => '36','name' => 'Amini'),
            array('id' => '1106','state_id' => '36','name' => 'Amdroth'),
            array('id' => '1107','state_id' => '36','name' => 'Kadmath'),
            array('id' => '1108','state_id' => '36','name' => 'Kalpeni'),
            array('id' => '1109','state_id' => '36','name' => 'Kavaratti'),
            array('id' => '1110','state_id' => '36','name' => 'Kilatan'),
            array('id' => '1111','state_id' => '36','name' => 'Chetlath'),
            array('id' => '1112','state_id' => '36','name' => 'Bithra'),
            array('id' => '1113','state_id' => '36','name' => 'Minicoy'),
            array('id' => '1115','state_id' => '25','name' => 'Mulugu'),
            array('id' => '1116','state_id' => '5','name' => 'Raipur city'),
            array('id' => '1117','state_id' => '5','name' => 'Raipur Rural'),
            array('id' => '1498','state_id' => '5','name' => 'Balodabazar'),
            array('id' => '1499','state_id' => '5','name' => 'Gariyaband'),
            array('id' => '1500','state_id' => '5','name' => 'Mahasamund'),
            array('id' => '1501','state_id' => '5','name' => 'Dhamtri'),
            array('id' => '1502','state_id' => '5','name' => 'Bhilai'),
            array('id' => '1503','state_id' => '5','name' => 'Durg'),
            array('id' => '1504','state_id' => '5','name' => 'Balod'),
            array('id' => '1505','state_id' => '5','name' => 'Bemetra'),
            array('id' => '1506','state_id' => '5','name' => 'Rajnandgoan'),
            array('id' => '1537','state_id' => '5','name' => 'Kondagoan'),
            array('id' => '1538','state_id' => '5','name' => 'Narayanpur'),
            array('id' => '1539','state_id' => '5','name' => 'Bastar'),
            array('id' => '1540','state_id' => '5','name' => 'Dantewada'),
            array('id' => '1546','state_id' => '5','name' => 'Bijapur'),
            array('id' => '1547','state_id' => '5','name' => 'Bilaspur'),
            array('id' => '1548','state_id' => '5','name' => 'Mungeli'),
            array('id' => '1549','state_id' => '5','name' => 'Janjgir Champa'),
            array('id' => '1550','state_id' => '5','name' => 'Korba'),
            array('id' => '1551','state_id' => '5','name' => 'Raigarh'),
            array('id' => '1552','state_id' => '5','name' => 'Jashpur'),
            array('id' => '1581','state_id' => '5','name' => 'Balrampur'),
            array('id' => '1582','state_id' => '5','name' => 'Koria'),
            array('id' => '1583','state_id' => '5','name' => 'Sarguja'),
            array('id' => '1584','state_id' => '5','name' => 'Kanker'),
            array('id' => '1585','state_id' => '5','name' => 'Surajpur'),
            array('id' => '1593','state_id' => '5','name' => 'Sukma'),
            array('id' => '1601','state_id' => '5','name' => 'Kawardha'),
            array('id' => '1602','state_id' => '22','name' => 'Shri Ganganagar'),
            array('id' => '1603','state_id' => '22','name' => 'Hanumangarh'),
            array('id' => '1604','state_id' => '22','name' => 'Bikaner Dehat'),
            array('id' => '1605','state_id' => '22','name' => 'Bikaner Shahar'),
            array('id' => '1606','state_id' => '22','name' => 'Churu'),
            array('id' => '1607','state_id' => '22','name' => 'Jhunjhunu'),
            array('id' => '1608','state_id' => '22','name' => 'Sikar'),
            array('id' => '1609','state_id' => '22','name' => 'Pali'),
            array('id' => '1610','state_id' => '22','name' => 'Barmer'),
            array('id' => '1611','state_id' => '22','name' => 'Jaipur Dehat Uttar'),
            array('id' => '1612','state_id' => '22','name' => 'Jaipur Dehat Dakshin'),
            array('id' => '1613','state_id' => '22','name' => 'Jaipur Shahar'),
            array('id' => '1614','state_id' => '22','name' => 'Alwar Dakshin'),
            array('id' => '1615','state_id' => '22','name' => 'Udaipur Shahar'),
            array('id' => '1616','state_id' => '22','name' => 'Bharatpur'),
            array('id' => '1617','state_id' => '22','name' => 'Dholpur'),
            array('id' => '1624','state_id' => '22','name' => 'Karauli'),
            array('id' => '1625','state_id' => '22','name' => 'Dausa'),
            array('id' => '1626','state_id' => '22','name' => 'Sawai Madhopur'),
            array('id' => '1627','state_id' => '22','name' => 'Tonk'),
            array('id' => '1628','state_id' => '22','name' => 'Ajmer Dehat'),
            array('id' => '1629','state_id' => '22','name' => 'Ajmer Shahar'),
            array('id' => '1630','state_id' => '22','name' => 'Bhilwara'),
            array('id' => '1631','state_id' => '22','name' => 'Nagaur Dehat'),
            array('id' => '1632','state_id' => '22','name' => 'Nagaur Shahar'),
            array('id' => '1633','state_id' => '22','name' => 'Chittorgarh'),
            array('id' => '1634','state_id' => '22','name' => 'Jodhpur Dehat Uttar'),
            array('id' => '1635','state_id' => '22','name' => 'Jodhpur Dehat Dakshin'),
            array('id' => '1636','state_id' => '22','name' => 'Jodhpur Shahar'),
            array('id' => '1637','state_id' => '22','name' => 'Jaisalmer'),
            array('id' => '1638','state_id' => '22','name' => 'Balotra'),
            array('id' => '1639','state_id' => '22','name' => 'Jalore'),
            array('id' => '1640','state_id' => '22','name' => 'Sirohi'),
            array('id' => '1641','state_id' => '22','name' => 'Udaipur Dehat'),
            array('id' => '1642','state_id' => '22','name' => 'Dungarpur'),
            array('id' => '1643','state_id' => '22','name' => 'Banswara'),
            array('id' => '1644','state_id' => '22','name' => 'Jhalawar'),
            array('id' => '1645','state_id' => '22','name' => 'Pratapgarh'),
            array('id' => '1653','state_id' => '22','name' => 'Rajsamand'),
            array('id' => '1654','state_id' => '22','name' => 'Bundi'),
            array('id' => '1655','state_id' => '22','name' => 'Kota Dehat'),
            array('id' => '1656','state_id' => '22','name' => 'Kota Shahar'),
            array('id' => '1657','state_id' => '22','name' => 'Baran'),
            array('id' => '1658','state_id' => '25','name' => 'Narayanpet'),
            array('id' => '1910','state_id' => '27','name' => 'Uttarkashi'),
            array('id' => '1911','state_id' => '27','name' => 'Chamoli'),
            array('id' => '1912','state_id' => '27','name' => 'Rudraprayag'),
            array('id' => '1913','state_id' => '27','name' => 'Tehri'),
            array('id' => '1914','state_id' => '27','name' => 'Dehradun Gramin'),
            array('id' => '1915','state_id' => '27','name' => 'Dehradun Mahanagar'),
            array('id' => '1916','state_id' => '27','name' => 'Haridwar'),
            array('id' => '1917','state_id' => '27','name' => 'Pauri'),
            array('id' => '1918','state_id' => '27','name' => 'Pithoragarh'),
            array('id' => '1919','state_id' => '27','name' => 'Bageshwar'),
            array('id' => '1920','state_id' => '27','name' => 'Almora'),
            array('id' => '1921','state_id' => '27','name' => 'Champawat'),
            array('id' => '1922','state_id' => '27','name' => 'Nainital'),
            array('id' => '1923','state_id' => '27','name' => 'Udhamsingh Nagar'),
            array('id' => '1924','state_id' => '29','name' => 'Kolkata North Suburban'),
            array('id' => '1925','state_id' => '29','name' => 'Jadavpur'),
            array('id' => '1926','state_id' => '29','name' => 'Mathurapur'),
            array('id' => '1927','state_id' => '29','name' => 'Diamond Harbour'),
            array('id' => '1928','state_id' => '29','name' => 'Kolkata South'),
            array('id' => '1929','state_id' => '29','name' => 'Kolkata North'),
            array('id' => '1930','state_id' => '29','name' => 'Jangipur'),
            array('id' => '1931','state_id' => '29','name' => 'Beharampur'),
            array('id' => '1932','state_id' => '29','name' => 'Nadia Uttar'),
            array('id' => '1933','state_id' => '29','name' => 'Nadia Dakshin'),
            array('id' => '1934','state_id' => '29','name' => 'Barasat'),
            array('id' => '1935','state_id' => '29','name' => 'Basirhat'),
            array('id' => '1936','state_id' => '29','name' => 'Barrackpore'),
            array('id' => '1937','state_id' => '29','name' => 'Coochbehar'),
            array('id' => '1938','state_id' => '29','name' => 'Alipurduar'),
            array('id' => '1939','state_id' => '29','name' => 'Jalpaiguri'),
            array('id' => '1940','state_id' => '29','name' => 'Siliguri'),
            array('id' => '1941','state_id' => '29','name' => 'Darjeeling'),
            array('id' => '1942','state_id' => '29','name' => 'Uttar Dinajpur'),
            array('id' => '1943','state_id' => '29','name' => 'Dakshin Dinajpur'),
            array('id' => '1944','state_id' => '29','name' => 'Malda Dakshin'),
            array('id' => '1945','state_id' => '29','name' => 'Purulia'),
            array('id' => '1946','state_id' => '29','name' => 'Bankura'),
            array('id' => '1948','state_id' => '29','name' => 'Burdwan'),
            array('id' => '1949','state_id' => '29','name' => 'Katwa'),
            array('id' => '1950','state_id' => '29','name' => 'Asansol'),
            array('id' => '1951','state_id' => '29','name' => 'Birbhum'),
            array('id' => '1952','state_id' => '29','name' => 'Howrah Town'),
            array('id' => '1953','state_id' => '29','name' => 'Howrah Gramin'),
            array('id' => '1954','state_id' => '29','name' => 'Sreerampur'),
            array('id' => '1955','state_id' => '29','name' => 'Hooghly'),
            array('id' => '1956','state_id' => '29','name' => 'Arambagh'),
            array('id' => '1957','state_id' => '29','name' => 'Tamluk'),
            array('id' => '1958','state_id' => '29','name' => 'Kanthi'),
            array('id' => '1959','state_id' => '29','name' => 'Ghatal'),
            array('id' => '1960','state_id' => '29','name' => 'Jhargram'),
            array('id' => '1961','state_id' => '29','name' => 'Mednipur'),
            array('id' => '2839','state_id' => '28','name' => 'Ambedkar Nagar'),
            array('id' => '2840','state_id' => '28','name' => 'Ayodhya Jila'),
            array('id' => '2841','state_id' => '28','name' => 'Ayodhya Mahanagar'),
            array('id' => '2842','state_id' => '28','name' => 'Unnav'),
            array('id' => '2843','state_id' => '28','name' => 'Gonda'),
            array('id' => '2845','state_id' => '28','name' => 'Bahraich'),
            array('id' => '2846','state_id' => '28','name' => 'Barabanki'),
            array('id' => '2847','state_id' => '28','name' => 'Raebareli'),
            array('id' => '2848','state_id' => '28','name' => 'Lucknow Jila'),
            array('id' => '2849','state_id' => '28','name' => 'Lucknow Mahanagar'),
            array('id' => '2850','state_id' => '28','name' => 'Lakhimpur Khiri'),
            array('id' => '2851','state_id' => '28','name' => 'Sitapur'),
            array('id' => '2852','state_id' => '28','name' => 'Hardoi'),
            array('id' => '2853','state_id' => '28','name' => 'Aligarh Jila'),
            array('id' => '2854','state_id' => '28','name' => 'Aligarh Mahanagar'),
            array('id' => '2855','state_id' => '28','name' => 'Aonla'),
            array('id' => '2856','state_id' => '28','name' => 'Agra Jila'),
            array('id' => '2857','state_id' => '28','name' => 'Etah'),
            array('id' => '2858','state_id' => '28','name' => 'Pilibhit'),
            array('id' => '2859','state_id' => '28','name' => 'Firozabad Jila'),
            array('id' => '2860','state_id' => '28','name' => 'Firozabad Mahanagar'),
            array('id' => '2861','state_id' => '28','name' => 'Budaun'),
            array('id' => '2862','state_id' => '28','name' => 'Bareilly Jila'),
            array('id' => '2863','state_id' => '28','name' => 'Mathura Jila'),
            array('id' => '2864','state_id' => '28','name' => 'Mathura Mahanagar'),
            array('id' => '2865','state_id' => '28','name' => 'Mainpuri'),
            array('id' => '2866','state_id' => '28','name' => 'Shahjahapur Jila'),
            array('id' => '2867','state_id' => '28','name' => 'Shahjahapur Mahanagar'),
            array('id' => '2868','state_id' => '28','name' => 'Hathras'),
            array('id' => '2869','state_id' => '28','name' => 'Gorakhpur Jila'),
            array('id' => '2870','state_id' => '28','name' => 'Gorakhpur Mahanagar'),
            array('id' => '2871','state_id' => '28','name' => 'Ballia'),
            array('id' => '2872','state_id' => '28','name' => 'Basti'),
            array('id' => '2873','state_id' => '28','name' => 'Mau'),
            array('id' => '2874','state_id' => '28','name' => 'Maharajganj'),
            array('id' => '2875','state_id' => '28','name' => 'Lalganj'),
            array('id' => '2876','state_id' => '28','name' => 'Santkabir Nagar'),
            array('id' => '2877','state_id' => '28','name' => 'Siddharthnagar'),
            array('id' => '2878','state_id' => '28','name' => 'Etawah'),
            array('id' => '2879','state_id' => '28','name' => 'Auraiya'),
            array('id' => '2880','state_id' => '28','name' => 'Kannauj'),
            array('id' => '2881','state_id' => '28','name' => 'Kanpur Uttar'),
            array('id' => '2882','state_id' => '28','name' => 'Kanpur Gramin'),
            array('id' => '2883','state_id' => '28','name' => 'Kanpur Dakshin'),
            array('id' => '2884','state_id' => '28','name' => 'Kanpur Dehat'),
            array('id' => '2885','state_id' => '28','name' => 'Chitrakoot'),
            array('id' => '2886','state_id' => '28','name' => 'Jalaun'),
            array('id' => '2887','state_id' => '28','name' => 'Fatehpur'),
            array('id' => '2888','state_id' => '28','name' => 'Farrukhabad'),
            array('id' => '2889','state_id' => '28','name' => 'Banda'),
            array('id' => '2890','state_id' => '28','name' => 'Mahoba'),
            array('id' => '2891','state_id' => '28','name' => 'Lalitpur'),
            array('id' => '2893','state_id' => '28','name' => 'Amethi'),
            array('id' => '2894','state_id' => '28','name' => 'Kaushambi'),
            array('id' => '2895','state_id' => '28','name' => 'Ghazipur'),
            array('id' => '2896','state_id' => '28','name' => 'Chandauli'),
            array('id' => '2897','state_id' => '28','name' => 'Jaunpur'),
            array('id' => '2899','state_id' => '28','name' => 'Prayagraj Gangapar'),
            array('id' => '2900','state_id' => '28','name' => 'Prayagraj Mahanagar'),
            array('id' => '2901','state_id' => '28','name' => 'Prayagraj Yamunapar'),
            array('id' => '2902','state_id' => '28','name' => 'Bhadohi'),
            array('id' => '2903','state_id' => '28','name' => 'Machhlishahar'),
            array('id' => '2904','state_id' => '28','name' => 'Mirzapur'),
            array('id' => '2905','state_id' => '28','name' => 'Varanasi Jila'),
            array('id' => '2906','state_id' => '28','name' => 'Varanasi Mahanagar'),
            array('id' => '2907','state_id' => '28','name' => 'Sonbhadra'),
            array('id' => '2908','state_id' => '28','name' => 'Amroha'),
            array('id' => '2909','state_id' => '28','name' => 'Ghaziabad Zila'),
            array('id' => '2910','state_id' => '28','name' => 'Ghaziabad Mahanagar'),
            array('id' => '2911','state_id' => '28','name' => 'Gautambudh Nagar'),
            array('id' => '2912','state_id' => '28','name' => 'Noida Mahanagar'),
            array('id' => '2913','state_id' => '28','name' => 'Baghpat'),
            array('id' => '2914','state_id' => '28','name' => 'Bijnor'),
            array('id' => '2915','state_id' => '28','name' => 'Bulandashahar'),
            array('id' => '2916','state_id' => '28','name' => 'Muzaffarnagar'),
            array('id' => '2917','state_id' => '28','name' => 'Muradabad Jila'),
            array('id' => '2918','state_id' => '28','name' => 'Muradabad Mahanagar'),
            array('id' => '2919','state_id' => '28','name' => 'Meerut Zila'),
            array('id' => '2920','state_id' => '28','name' => 'Meerut Mahanagar'),
            array('id' => '2921','state_id' => '28','name' => 'Sambhal'),
            array('id' => '2922','state_id' => '28','name' => 'Saharanpur Jila'),
            array('id' => '2923','state_id' => '28','name' => 'Saharanpur Mahanagar'),
            array('id' => '2924','state_id' => '28','name' => 'Hapur'),
            array('id' => '2925','state_id' => '28','name' => 'Agra Mahanagar'),
            array('id' => '2926','state_id' => '28','name' => 'Aazamgarh'),
            array('id' => '2927','state_id' => '28','name' => 'Kasganj'),
            array('id' => '2928','state_id' => '28','name' => 'Kushinagar'),
            array('id' => '2929','state_id' => '28','name' => 'Jhansi Jila'),
            array('id' => '2930','state_id' => '28','name' => 'Jhansi Mahanagar'),
            array('id' => '2931','state_id' => '28','name' => 'Deoria'),
            array('id' => '2932','state_id' => '28','name' => 'Bareilly Mahanagar'),
            array('id' => '2933','state_id' => '28','name' => 'Rampur'),
            array('id' => '2934','state_id' => '28','name' => 'Shamli'),
            array('id' => '2935','state_id' => '28','name' => 'Shravasti'),
            array('id' => '2936','state_id' => '28','name' => 'Sultanpur'),
            array('id' => '2937','state_id' => '13','name' => 'Kasaragod'),
            array('id' => '2938','state_id' => '13','name' => 'Kannur'),
            array('id' => '2939','state_id' => '13','name' => 'Kozhikode'),
            array('id' => '2940','state_id' => '13','name' => 'Wayanad'),
            array('id' => '2941','state_id' => '13','name' => 'Malappuram'),
            array('id' => '2942','state_id' => '13','name' => 'Palakkad'),
            array('id' => '2943','state_id' => '13','name' => 'Thrissur'),
            array('id' => '2944','state_id' => '13','name' => 'Ernakulam'),
            array('id' => '2945','state_id' => '13','name' => 'Idukki'),
            array('id' => '2946','state_id' => '13','name' => 'Kottayam'),
            array('id' => '2947','state_id' => '13','name' => 'Alappuzha'),
            array('id' => '2948','state_id' => '13','name' => 'Pathanamthitta'),
            array('id' => '2949','state_id' => '13','name' => 'Kollam'),
            array('id' => '2950','state_id' => '13','name' => 'Thiruvananthapuram'),
            array('id' => '2951','state_id' => '22','name' => 'Alwar Uttar'),
            array('id' => '2952','state_id' => '12','name' => 'Bengaluru Central'),
            array('id' => '2962','state_id' => '2','name' => 'Pakke Kessang'),
            array('id' => '2963','state_id' => '2','name' => 'Leparada'),
            array('id' => '2964','state_id' => '2','name' => 'Shi Yomi'),
            array('id' => '2965','state_id' => '1','name' => 'Amalapuram'),
            array('id' => '2967','state_id' => '1','name' => 'Araku'),
            array('id' => '2968','state_id' => '1','name' => 'Hindupur'),
            array('id' => '2969','state_id' => '1','name' => 'Bapatla'),
            array('id' => '2970','state_id' => '1','name' => 'Narasaraopeta'),
            array('id' => '2971','state_id' => '1','name' => 'Rajampet'),
            array('id' => '2972','state_id' => '1','name' => 'Tirupati'),
            array('id' => '2973','state_id' => '1','name' => 'Eluru'),
            array('id' => '2974','state_id' => '1','name' => 'Parvathipuram'),
            array('id' => '2975','state_id' => '1','name' => 'Nandyal'),
            array('id' => '2976','state_id' => '38','name' => 'Zanskar'),
            array('id' => '2977','state_id' => '11','name' => 'Dhanbad Rural'),
            array('id' => '2978','state_id' => '15','name' => 'Raigad North'),
            array('id' => '2979','state_id' => '15','name' => 'Ratnagiri North'),
            array('id' => '3022','state_id' => '32','name' => 'Daman'),
            array('id' => '3023','state_id' => '32','name' => 'Diu'),
            array('id' => '3024','state_id' => '15','name' => 'Nagar North'),
            array('id' => '3045','state_id' => '24','name' => 'North Chennai East'),
            array('id' => '3046','state_id' => '24','name' => 'North Chennai West'),
            array('id' => '3047','state_id' => '24','name' => 'Central Chennai West'),
            array('id' => '3049','state_id' => '24','name' => 'Chennai East'),
            array('id' => '3050','state_id' => '24','name' => 'Chengalpattu North'),
            array('id' => '3051','state_id' => '24','name' => 'Kanchipuram'),
            array('id' => '3052','state_id' => '24','name' => 'Ranipet'),
            array('id' => '3053','state_id' => '24','name' => 'Vellore'),
            array('id' => '3054','state_id' => '24','name' => 'Tirupattur'),
            array('id' => '3055','state_id' => '24','name' => 'Krishnagiri East'),
            array('id' => '3058','state_id' => '24','name' => 'Kallakurichi'),
            array('id' => '3059','state_id' => '24','name' => 'Dindigul West'),
            array('id' => '3060','state_id' => '24','name' => 'Dindigul East'),
            array('id' => '3061','state_id' => '24','name' => 'Virudhunagar West'),
            array('id' => '3062','state_id' => '24','name' => 'Virudhunagar East'),
            array('id' => '3063','state_id' => '24','name' => 'Thoothukudi North'),
            array('id' => '3064','state_id' => '24','name' => 'Thoothukudi South'),
            array('id' => '3065','state_id' => '24','name' => 'Tenkasi'),
            array('id' => '3066','state_id' => '24','name' => 'Tirunelveli North'),
            array('id' => '3068','state_id' => '24','name' => 'Chennai West'),
            array('id' => '3069','state_id' => '24','name' => 'Kanyakumari'),
            array('id' => '3070','state_id' => '25','name' => 'Golconda Goshamahal'),
            array('id' => '3071','state_id' => '25','name' => 'Bhagyanagar Malakpet'),
            array('id' => '3072','state_id' => '25','name' => 'Mahankali Secunderabad'),
            array('id' => '3073','state_id' => '25','name' => 'Medchal Malkajgiri Rural'),
            array('id' => '3074','state_id' => '25','name' => 'Rangareddy Rural'),
            array('id' => '3075','state_id' => '38','name' => 'Nubra'),
            array('id' => '3076','state_id' => '33','name' => 'Mayabunder'),
            array('id' => '3077','state_id' => '29','name' => 'Bongaon'),
            array('id' => '3078','state_id' => '14','name' => 'Niwari'),
            array('id' => '3080','state_id' => '34','name' => 'Shaheed Bhagat Singh Nagar'),
            array('id' => '3081','state_id' => '5','name' => 'Gorela Pendra Marwahi'),
            array('id' => '3084','state_id' => '21','name' => 'Ludhiana Rural'),
            array('id' => '3086','state_id' => '21','name' => 'Malerkotla'),
            array('id' => '3087','state_id' => '3','name' => 'Tamulpur'),
            array('id' => '3089','state_id' => '23','name' => 'Pakyong'),
            array('id' => '3090','state_id' => '23','name' => 'Geyzing'),
            array('id' => '3091','state_id' => '12','name' => 'Vijayanagara'),
            array('id' => '3092','state_id' => '12','name' => 'Madhugiri'),
            array('id' => '3093','state_id' => '29','name' => 'Malda Uttar'),
            array('id' => '3094','state_id' => '29','name' => 'Bolpur'),
            array('id' => '3095','state_id' => '29','name' => 'Joynagar'),
            array('id' => '3096','state_id' => '32','name' => 'Silvasa Saher'),
            array('id' => '3097','state_id' => '27','name' => 'Kashipur'),
            array('id' => '3098','state_id' => '27','name' => 'Ranikhet'),
            array('id' => '3099','state_id' => '27','name' => 'Rishikesh'),
            array('id' => '3100','state_id' => '27','name' => 'Roorkee'),
            array('id' => '3101','state_id' => '27','name' => 'Kotdwar'),
            array('id' => '3102','state_id' => '5','name' => 'Sarangarh'),
            array('id' => '3103','state_id' => '5','name' => 'Khairagarh-Chhuikhadan-Gandai'),
            array('id' => '3104','state_id' => '5','name' => 'Mohla-Manpur-Ambagarh Chowki'),
            array('id' => '3105','state_id' => '5','name' => 'Sakti'),
            array('id' => '3106','state_id' => '5','name' => 'Manendragarh-Chirmiri-Bharatpur'),
            array('id' => '3128','state_id' => '24','name' => 'Tirunelveli South'),
            array('id' => '3129','state_id' => '24','name' => 'Madurai East'),
            array('id' => '3130','state_id' => '24','name' => 'Pudukkottai West'),
            array('id' => '3131','state_id' => '24','name' => 'Villupuram South'),
            array('id' => '3132','state_id' => '24','name' => 'Chengalpattu South'),
            array('id' => '3133','state_id' => '24','name' => 'Namakkal East'),
            array('id' => '3135','state_id' => '29','name' => 'Murshidabad'),
            array('id' => '3136','state_id' => '15','name' => 'Jalgaon Purv'),
            array('id' => '3137','state_id' => '15','name' => 'Kolhapur (Purv)'),
            array('id' => '3138','state_id' => '15','name' => 'Nanded Uttar'),
            array('id' => '3139','state_id' => '15','name' => 'Nashik Dakshin'),
            array('id' => '3140','state_id' => '15','name' => 'Pune (Dakshin Baramati)'),
            array('id' => '3141','state_id' => '15','name' => 'Sambhaji Nagar Uttar'),
            array('id' => '3142','state_id' => '15','name' => 'Solapur (Paschim Madha)'),
            array('id' => '3143','state_id' => '15','name' => 'Khamgaon'),
            array('id' => '3144','state_id' => '15','name' => 'Pusad'),
            array('id' => '3147','state_id' => '17','name' => 'Eastern West Khasi Hills'),
            array('id' => '3148','state_id' => '14','name' => 'Maihar'),
            array('id' => '3149','state_id' => '14','name' => 'Pandhurna'),
            array('id' => '3150','state_id' => '14','name' => 'Mauganj')
        ));

        $batchSize = 500;

        Zilla::truncate();

        $collection->chunk($batchSize)->each(function ($chunk) {
            Zilla::insert($chunk->toArray());
        });

        Zilla::query()->update([
            'created_at' => now(),
            'updated_at' => now()
        ]);
    }
}
